"""The external checks, and the independent-versus-circular accounting they carry.

This is the module the package calls its most important idea, and it had no test
file at all until an adversarial review pointed that out: EXT-02 and EXT-04 could
be deleted outright and the suite stayed green.

The distinction being pinned here is not a style preference. The submission SDFs
were generated by asking PubChem about each CAS number, so a PubChem agreement is
a source confirming itself. On the reference batch that "confirmed" 284 of 290
records; measured properly, only 259 are corroborated by a source of a different
origin and 31 rest entirely on PubChem.
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

import pytest

from chebi_gate import casreg, chebi_release, checks, external, formula, sdf, structure
from chebi_gate.checks import HIGH, INFO, LOW, MEDIUM
from tests.chebi_gate_helpers import ISA_HYDROCHLORIDE, salt_record, sdf_bytes

CAS = "557-66-4"
WRONG_KEY = "ZZZZZZZZZZZZZZ-ZZZZZZZZZZ-Z"


@pytest.fixture
def ctx() -> checks.RecordContext:
    record = sdf.parse_bytes(sdf_bytes(salt_record(iupac="x"))).records[0]
    return checks.RecordContext(record=record, structure=structure.analyse(record))


@pytest.fixture
def drawn_key(ctx) -> str:
    return ctx.structure.inchikey


def registry(tmp_path: Path, **row) -> casreg.Registry:
    path = tmp_path / f"reg{len(list(tmp_path.glob('reg*.csv')))}.csv"
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(casreg.REGISTRY_COLUMNS))
        writer.writeheader()
        writer.writerow({**{c: "" for c in casreg.REGISTRY_COLUMNS}, "cas": CAS, **row})
    return casreg.load(path)


def pubchem(tmp_path: Path, name: str, **body) -> Path:
    directory = tmp_path / name
    directory.mkdir()
    payload = {
        "cas": CAS,
        "cids_status": 200,
        "cids": [1],
        "cid": 1,
        "property_status": 200,
        "properties": {"InChIKey": WRONG_KEY, "MolecularFormula": "C2H8ClN"},
        "status": "ok",
    }
    payload.update(body)
    (directory / f"{CAS}.json").write_text(json.dumps(payload))
    return directory


def chebi_index(tmp_path: Path, *rows: tuple[str, str, str]) -> chebi_release.Index:
    release = tmp_path / f"rel{len(list(tmp_path.glob('rel*')))}"
    release.mkdir()
    (release / "structures.tsv").write_text(
        "compound_id\tstandard_inchi_key\n"
        + "".join(f"{cid}\t{key}\n" for cid, key, _ in rows)
    )
    (release / "compounds.tsv").write_text(
        "id\tascii_name\tstars\n"
        + "".join(f"{cid}\t{name}\t3\n" for cid, _, name in rows)
    )
    (release / "database_accession.tsv").write_text(
        "compound_id\taccession_number\ttype\n"
    )
    return chebi_release.distil(release, tmp_path / f"idx{release.name}", generated="x")


def ext01(evidence, ctx) -> list:
    return list(external.ext01(evidence, ctx))


# ------------------------------------------------------- EXT-01, source ranking


def test_no_configured_source_means_the_check_did_not_run(ctx):
    """ "We could not look" is a fact about the run, not a finding about a record.

    Emitting it per record put a medium finding on all 290 and held the batch.
    """
    assert external.Evidence().resolves_cas is False
    assert ext01(external.Evidence(), ctx) == []


def test_an_exact_match_from_an_independent_source_is_silent(tmp_path, ctx, drawn_key):
    evidence = external.Evidence(registry=registry(tmp_path, inchikey=drawn_key))
    assert ext01(evidence, ctx) == []
    assert external.resolve_cas(evidence, ctx).corroborated is True


def test_a_circular_exact_match_is_reported_at_low_severity(tmp_path, ctx, drawn_key):
    """PubChem agreeing with a file generated from PubChem is not verification.

    It holds nothing -- the record is fine as far as anyone can tell -- but it must
    not be counted among the confirmations.
    """
    evidence = external.Evidence(
        registry=registry(tmp_path, inchikey=""),
        pubchem_dir=pubchem(tmp_path, "pc", properties={"InChIKey": drawn_key}),
    )
    verdict = external.resolve_cas(evidence, ctx)
    assert verdict.status == external.EXACT
    assert verdict.corroborated is False

    (finding,) = ext01(evidence, ctx)
    assert finding.severity == LOW
    assert finding.is_independent is False
    assert "only in the source the file was generated from" in finding.detail


def test_a_circular_match_does_not_erase_an_independent_disagreement(
    tmp_path, ctx, drawn_key
):
    """The registry cannot refute, so this is about not losing the *record* of it."""
    evidence = external.Evidence(
        registry=registry(tmp_path, inchikey=WRONG_KEY),
        pubchem_dir=pubchem(tmp_path, "pc", properties={"InChIKey": drawn_key}),
    )
    verdict = external.resolve_cas(evidence, ctx)
    assert verdict.status == external.EXACT
    assert verdict.corroborated is False, (
        "an independent source that disagreed has not corroborated anything"
    )
    (finding,) = ext01(evidence, ctx)
    assert finding.severity == LOW
    assert WRONG_KEY in finding.detail, "the disagreeing source must still be named"


def test_candidates_are_ordered_independent_first(tmp_path, ctx, drawn_key):
    """The ordering is the mechanism, so it is what gets pinned.

    resolve_cas takes the best-ranked candidate and keeps the earliest of equal
    ranks, so this order is the only thing stopping a circular confirmation from
    displacing an independent one of the same strength. A redundant tiebreak in
    the sort key used to sit alongside it; mutation testing showed no test could
    tell the two apart, because they always agreed. One mechanism, pinned here.
    """
    evidence = external.Evidence(
        registry=registry(tmp_path, inchikey=drawn_key),
        common_chemistry_dir=tmp_path / "absent",
        pubchem_dir=pubchem(tmp_path, "pc", properties={"InChIKey": drawn_key}),
    )
    candidates = external.gather_candidates(evidence, CAS)
    assert [c.independent for c in candidates] == [True, False]
    assert candidates[0].source == external.REGISTRY_SOURCE

    circular_first = list(reversed(candidates))
    assert [c.independent for c in circular_first] == [False, True], (
        "sanity: the reversed list is the ordering this test exists to forbid"
    )


def test_an_independent_confirmation_wins_a_tie_against_a_circular_one(
    tmp_path, ctx, drawn_key
):
    evidence = external.Evidence(
        registry=registry(tmp_path, inchikey=drawn_key),
        pubchem_dir=pubchem(tmp_path, "pc", properties={"InChIKey": drawn_key}),
    )
    verdict = external.resolve_cas(evidence, ctx)
    assert verdict.candidate.source == external.REGISTRY_SOURCE
    assert verdict.independent is True
    assert ext01(evidence, ctx) == []


def test_a_cas_source_can_confirm_but_never_refute(tmp_path, ctx):
    """Its structure strings are unreliable for salts.

    Measured on the batch: treating the SciFinder InChIKey as authoritative turns
    25 sound records into high findings -- 7-NINA sodium salt is registered as the
    neutral acid plus Na against an ionic drawing, AY 9944 carries a pre-standard
    "InChI=1/" key with the same skeleton, cyanopindolol hemifumarate is registered
    as "1/2C4H4O4" against a doubled drawing. None is a defect.
    """
    evidence = external.Evidence(registry=registry(tmp_path, inchikey=WRONG_KEY))
    verdict = external.resolve_cas(evidence, ctx)
    assert verdict.status == external.UNRESOLVED
    assert not [f for f in ext01(evidence, ctx) if f.severity == HIGH]


def test_a_cas_source_never_downgrades_another_sources_exact_match(
    tmp_path, ctx, drawn_key
):
    """A registry skeleton match must not turn a PubChem exact match into skeleton.

    Preferring the independent source absolutely dropped 22 sound records from
    exact to skeleton.
    """
    evidence = external.Evidence(
        registry=registry(tmp_path, inchikey=drawn_key[:14] + "-QQQQQQQQQQ-N"),
        pubchem_dir=pubchem(tmp_path, "pc", properties={"InChIKey": drawn_key}),
    )
    assert external.resolve_cas(evidence, ctx).status == external.EXACT


def test_pubchem_may_refute_and_the_finding_is_flagged_circular(tmp_path, ctx):
    evidence = external.Evidence(pubchem_dir=pubchem(tmp_path, "pc"))
    (finding,) = ext01(evidence, ctx)
    assert finding.severity == HIGH
    assert finding.is_independent is False
    assert "different skeleton" in finding.detail


def test_a_parent_only_match_is_medium(tmp_path, ctx):
    parent = ctx.structure.base_inchikey
    evidence = external.Evidence(
        pubchem_dir=pubchem(tmp_path, "pc", properties={"InChIKey": parent})
    )
    (finding,) = ext01(evidence, ctx)
    assert finding.severity == MEDIUM
    assert "free base or another salt form" in finding.detail


# --------------------------------------------------- EXT-01, cached failures


@pytest.mark.parametrize(
    "body",
    [
        {"cids_status": 503, "properties": {}, "status": "error"},
        {"cids_status": 500, "properties": {}, "status": "error"},
    ],
)
def test_a_cached_transient_failure_is_not_read_as_a_negative(tmp_path, ctx, body):
    """Handoff case 10. One record was falsely unresolved this way.

    The caches persist the HTTP status, but nothing in the prototype read it, so
    "no such compound" and "the service was down for eight seconds" were
    byte-for-byte indistinguishable and both came out as unresolved.
    """
    evidence = external.Evidence(pubchem_dir=pubchem(tmp_path, "pc", **body))
    verdict = external.resolve_cas(evidence, ctx)
    assert verdict.status == external.UNAVAILABLE
    (finding,) = ext01(evidence, ctx)
    assert "cached response was a failure" in finding.detail
    assert "re-fetch" in finding.detail


def test_a_real_negative_is_still_a_negative(tmp_path, ctx):
    evidence = external.Evidence(
        pubchem_dir=pubchem(tmp_path, "pc", cids_status=404, cids=[], properties={})
    )
    assert external.resolve_cas(evidence, ctx).status == external.UNRESOLVED


def test_unavailable_outranks_unresolved_so_an_unknown_is_never_a_negative():
    """If one source is down and another has nothing, the answer is "we do not know"."""
    assert external.RANK[external.UNAVAILABLE] < external.RANK[external.UNRESOLVED]


def test_every_cid_is_evaluated_not_just_the_first(tmp_path, ctx, drawn_key):
    """Handoff case 2: judging the first CID invented 3 stereo mismatches and 7
    wrong salt forms across the 22 records that resolved to more than one.
    """
    evidence = external.Evidence(
        pubchem_dir=pubchem(
            tmp_path,
            "pc",
            cids=[1, 2],
            properties={"InChIKey": WRONG_KEY},
            alt_cids={"2": {"InChIKey": drawn_key, "MolecularFormula": "C2H8ClN"}},
        )
    )
    verdict = external.resolve_cas(evidence, ctx)
    assert verdict.status == external.EXACT, "the matching sibling CID must be found"
    assert "CID 2" in verdict.candidate.detail


def test_the_multi_cid_count_is_reported(tmp_path, ctx, drawn_key):
    evidence = external.Evidence(
        pubchem_dir=pubchem(
            tmp_path, "pc", cids=[1, 2, 3], properties={"InChIKey": drawn_key}
        )
    )
    assert "of 3 returned" in external.resolve_cas(evidence, ctx).candidate.detail


def test_every_smiles_spelling_is_read(tmp_path, ctx, drawn_key):
    """PubChem renamed IsomericSMILES to SMILES in 2025 and still accepts the old
    name, returning HTTP 200 keyed by the new one -- so a fetcher retrying only on
    400 never retries. All 291 cached records carry SMILES and none IsomericSMILES.
    """
    assert "SMILES" in external.SMILES_KEYS
    assert "IsomericSMILES" in external.SMILES_KEYS
    for key in external.SMILES_KEYS:
        evidence = external.Evidence(
            pubchem_dir=pubchem(
                tmp_path,
                f"pc{key}",
                properties={"InChIKey": drawn_key, key: "CCN.Cl"},
            )
        )
        assert external.resolve_cas(evidence, ctx).status == external.EXACT


# --------------------------------------------------------------- EXT-02, EXT-03


def test_an_exact_chebi_match_is_a_duplicate_and_holds_the_record(
    tmp_path, ctx, drawn_key
):
    index = chebi_index(tmp_path, ("16236", drawn_key, "ethylamine hydrochloride"))
    (finding,) = list(external.ext02(external.Evidence(chebi=index), ctx))
    assert finding.severity == HIGH
    assert "already in ChEBI as CHEBI:16236" in finding.detail
    assert finding.is_independent is True


def test_every_owning_chebi_id_is_named(tmp_path, ctx, drawn_key):
    """1,453 of 188,378 keys in release 255 are owned by more than one entry."""
    index = chebi_index(
        tmp_path, ("16236", drawn_key, "one"), ("99999", drawn_key, "two")
    )
    (finding,) = list(external.ext02(external.Evidence(chebi=index), ctx))
    assert "CHEBI:16236" in finding.detail
    assert "CHEBI:99999" in finding.detail


def test_a_skeleton_match_is_a_relative_and_never_holds_the_record(
    tmp_path, ctx, drawn_key
):
    """It is explicitly not a duplicate, so it informs a curator and holds nothing.

    This was medium until the severities were checked against what the batch
    does: 38 of the 283 records already deposited would have been held by it under
    the default policy, every one for having a relative rather than a defect.
    """
    relative = drawn_key[:14] + "-QQQQQQQQQQ-N"
    index = chebi_index(tmp_path, ("16236", relative, "a relative"))
    (finding,) = list(external.ext02(external.Evidence(chebi=index), ctx))
    assert finding.severity == LOW
    assert "not a duplicate" in finding.detail
    assert MEDIUM not in checks.CHECKS["EXT-02"].severities


def test_no_chebi_match_is_silent(tmp_path, ctx):
    index = chebi_index(tmp_path, ("16236", "AAAAAAAAAAAAAA-BBBBBBBBBB-C", "other"))
    assert list(external.ext02(external.Evidence(chebi=index), ctx)) == []


def test_ext02_is_silent_with_no_release(ctx):
    assert list(external.ext02(external.Evidence(), ctx)) == []


def test_a_parent_in_chebi_is_an_info_has_part_candidate(tmp_path, ctx):
    parent = ctx.structure.base_inchikey
    index = chebi_index(tmp_path, ("114178", parent, "ethylamine"))
    (finding,) = list(external.ext03(external.Evidence(chebi=index), ctx))
    assert finding.severity == INFO
    assert "candidate has-part link" in finding.detail


def test_ext03_only_accepts_an_exact_parent_match(tmp_path, ctx):
    """Accepting skeleton matches took this from 165 candidates to 206."""
    parent = ctx.structure.base_inchikey
    index = chebi_index(tmp_path, ("114178", parent[:14] + "-QQQQQQQQQQ-N", "nearly"))
    assert list(external.ext03(external.Evidence(chebi=index), ctx)) == []


def test_ext03_does_not_fire_on_a_non_salt(tmp_path):
    record = sdf.parse_bytes(
        sdf_bytes(salt_record(mol="ethanol", relationship=None, iupac="x"))
    ).records[0]
    ctx = checks.RecordContext(
        record=record, structure=structure.analyse(record), role=checks.ROLE_NEUTRAL
    )
    index = chebi_index(tmp_path, ("16236", ctx.structure.base_inchikey, "ethanol"))
    assert list(external.ext03(external.Evidence(chebi=index), ctx)) == []


# ---------------------------------------------------------------------- EXT-04


def test_ext04_reports_a_disagreement_at_high(tmp_path, ctx):
    evidence = external.Evidence(
        registry=registry(tmp_path, molecular_formula="C6H15N3S.2ClH")
    )
    (finding,) = list(external.ext04(evidence, ctx))
    assert finding.severity == HIGH
    assert finding.is_independent is True
    assert "disagrees" in finding.detail


def test_ext04_reports_the_hydrogen_convention_at_info(tmp_path, ctx):
    evidence = external.Evidence(
        registry=registry(tmp_path, molecular_formula="C2H9ClN")
    )
    (finding,) = list(external.ext04(evidence, ctx))
    assert finding.severity == INFO
    assert "neutral-acid versus ionic" in finding.detail


def test_ext04_reports_an_indefinite_ratio_at_medium(tmp_path, ctx):
    evidence = external.Evidence(
        registry=registry(
            tmp_path, molecular_formula="C2H7N.xHCl", name_ratio="unknown-to-CAS"
        )
    )
    (finding,) = list(external.ext04(evidence, ctx))
    assert finding.severity == MEDIUM
    assert "does not fix the component ratio" in finding.detail


def test_ext04_reports_a_missing_registry_row_at_low(tmp_path, ctx):
    """Not a defect and not a pass: the record cannot be checked on this axis."""
    other = registry(tmp_path, molecular_formula="C2H8ClN")
    evidence = external.Evidence(registry=other)
    record = sdf.parse_bytes(sdf_bytes(salt_record(cas="64-17-5", iupac="x"))).records[
        0
    ]
    missing = checks.RecordContext(record=record, structure=structure.analyse(record))
    (finding,) = list(external.ext04(evidence, missing))
    assert finding.severity == LOW
    assert "unchecked" in finding.detail


def test_ext04_agrees_silently(tmp_path, ctx):
    evidence = external.Evidence(
        registry=registry(tmp_path, molecular_formula="C2H8ClN")
    )
    assert list(external.ext04(evidence, ctx)) == []


def test_ext04_does_not_fire_at_all_without_a_registry(ctx):
    """Otherwise every record in a 290-record batch carries a no-record finding."""
    assert list(external.ext04(external.Evidence(), ctx)) == []


def test_ext04_reads_stoichiometry_from_the_formula_not_the_inchi(tmp_path, ctx):
    """Handoff case 4, as it appears in the real table.

    Both indefinite-ratio records carry a formula saying the ratio is unknown and
    an InChI carrying a definite 1:1.
    """
    evidence = external.Evidence(
        registry=registry(
            tmp_path,
            molecular_formula="C2H7N.xHCl",
            name_ratio="unknown-to-CAS",
            inchi="InChI=1S/C2H7N.ClH/c1-2-3;/h3H2;1H",
        )
    )
    (finding,) = list(external.ext04(evidence, ctx))
    assert finding.severity == MEDIUM, (
        "the InChI's definite ratio must not turn 'unknown' into 'confirmed'"
    )


# ------------------------------------------------------------- source accounting


def test_available_sources_are_reported_and_split_by_origin(tmp_path, ctx, drawn_key):
    evidence = external.Evidence(
        registry=registry(tmp_path, inchikey=drawn_key),
        pubchem_dir=pubchem(tmp_path, "pc"),
        common_chemistry_dir=tmp_path / "missing",
    )
    assert external.REGISTRY_SOURCE in evidence.available
    assert external.PUBCHEM_SOURCE in evidence.available
    assert external.PUBCHEM_SOURCE not in evidence.independent_sources
    assert external.REGISTRY_SOURCE in evidence.independent_sources


def test_a_missing_cache_directory_is_simply_absent(tmp_path, ctx):
    evidence = external.Evidence(pubchem_dir=tmp_path / "nope")
    assert evidence.available == ()
    assert evidence.resolves_cas is False
    assert ext01(evidence, ctx) == []


def test_run_external_checks_validates_every_finding(tmp_path, ctx, drawn_key):
    evidence = external.Evidence(
        registry=registry(
            tmp_path, molecular_formula="C6H15N3S.2ClH", inchikey=drawn_key
        ),
        chebi=chebi_index(tmp_path, ("16236", drawn_key, "ethylamine hydrochloride")),
    )
    found = external.run_external_checks(evidence, ctx)
    assert found
    for finding in found:
        assert finding.check in checks.CHECKS
        assert finding.severity in checks.CHECKS[finding.check].severities
        assert finding.cas == CAS


def test_a_solvated_hydrohalide_still_satisfies_its_class():
    """A hydrated hydrochloride is a hydrochloride.

    The class rule demanded that *every* counterion be a halide, so any hydrate or
    ethanolate of a hydrohalide could never satisfy CON-01. Efonidipine
    hydrochloride monoethanolate is exactly that shape.
    """
    from chebi_gate import classes

    record = sdf.parse_bytes(
        sdf_bytes(
            salt_record(
                name="decylamine hydrochloride hydrate",
                mol="amine_hydrate",
                relationship=ISA_HYDROCHLORIDE,
                iupac="x",
            )
        )
    ).records[0]
    hydrate_only = structure.analyse(record)
    assert hydrate_only.counter == ["H2O"]
    # Water alone is not a hydrohalide: there is no halide to satisfy the class.
    assert classes.class_supported("hydrochloride", hydrate_only) is False

    from dataclasses import replace

    with_both = replace(hydrate_only, counter=["HCl", "H2O"])
    assert classes.class_supported("hydrochloride", with_both) is True, (
        "the water must not disqualify the hydrochloride"
    )
    assert classes.SOLVATES == ("H2O", "C2H6O")


def test_formula_comparison_is_reused_not_reimplemented():
    """EXT-04 must read the same comparator the formula tests pin."""
    assert external.formula_mod is formula


def test_ext04_does_not_hold_a_record_for_an_unreadable_registry_formula(tmp_path, ctx):
    """Both sides of UNPARSEABLE were HIGH, so a bad table cell held a good record.

    formula.py's own example is a vendor code that lost its space in a SciFinder
    export -- a defect in evidence assembled by hand from PDFs, not in the record.
    `Comparison.checked` already classes UNPARSEABLE with the statuses that
    checked nothing; the severity agrees with that now.
    """
    evidence = external.Evidence(
        registry=registry(tmp_path, molecular_formula="WAG994")
    )
    (finding,) = list(external.ext04(evidence, ctx))
    assert finding.severity == MEDIUM
    assert "could not be parsed" in finding.detail


def test_ext04_still_holds_a_record_whose_own_formula_is_unreadable():
    """The other side of the split: that one is the record's defect."""
    verdict = formula.compare("C2H6O", "WAG994")
    assert verdict.status == formula.UNPARSEABLE
    assert verdict.unparseable_side == "drawn"
    assert formula.compare("WAG994", "C2H6O").unparseable_side == "registry"


def test_a_cached_entry_with_no_inchikey_is_not_reported_as_no_cache_at_all(tmp_path):
    """The blob answers for this CAS; it just carries no key.

    The guard was `not entries`, so a blob with entries but no InChIKey returned
    nothing and the verdict read "no cached source holds this CAS number" about a
    number the cache had an entry for.
    """
    directory = pubchem(tmp_path, "no_key", properties={"MolecularFormula": "C2H7N"})
    evidence = external.Evidence(pubchem_dir=directory)
    candidates = external.pubchem_candidates(evidence, CAS)
    assert candidates and candidates[0].available
    assert candidates[0].inchikey is None


def test_a_properties_list_is_read_like_a_properties_mapping(tmp_path):
    """PubChem's own PropertyTable.Properties is a list; the writer is elsewhere."""
    directory = pubchem(tmp_path, "as_list", properties=[{"InChIKey": WRONG_KEY}])
    evidence = external.Evidence(pubchem_dir=directory)
    (candidate,) = external.pubchem_candidates(evidence, CAS)
    assert candidate.inchikey == WRONG_KEY
