"""The check registry: one function per check, each declaring what it is worth.

Every check carries three pieces of metadata beyond its logic:

``severity``
    Which severities it may emit. ``high`` always holds a record back, ``medium``
    holds unless the caller allows it, ``low`` and ``info`` never hold.

``independent``
    Whether the two things being compared have different origins. This is the most
    important field in the module and the reason the registry exists.

    The submission SDFs were generated by asking PubChem about each CAS number, so
    checking those SDFs against PubChem is asking a source to confirm itself. On
    the batch this was ported from, such a check passed 284 of 290 records, and the
    number is close to meaningless -- it mostly says the generation step ran. The
    same batch, checked against evidence of a different origin, showed
    efonidipine missing an ethanol fragment that the circular check had called
    flawless. So the summary reports the two kinds separately and never adds them
    together.

    A few checks are independent or circular *per finding* rather than per check:
    EXT-01 is circular when a CAS number resolved through the PubChem cache and
    independent when it resolved through the CAS registry export. Those set the
    flag on the finding.

``title``
    A plain-English sentence, so a report can say what was checked without the
    reader holding a table of check IDs in their head.

Checks are keyed on the CAS number, never on NAME. NAME is mutable display text:
renaming four records in the prototype silently broke every name-keyed join and
needed a rename map bolted on to paper over it.
"""

from __future__ import annotations

import logging
import re
from collections import defaultdict
from collections.abc import Callable, Iterator
from dataclasses import dataclass, replace

from . import classes
from .sdf import SdfRecord
from .structure import Structure

log = logging.getLogger(__name__)

HIGH = "high"
MEDIUM = "medium"
LOW = "low"
INFO = "info"

# Ordering for reports and for deciding a record's worst finding.
SEVERITY_RANK = {HIGH: 0, MEDIUM: 1, LOW: 2, INFO: 3}

ROLE_AUTO = "auto"
ROLE_SALT = "salt"
ROLE_NEUTRAL = "neutral"
ROLES = (ROLE_AUTO, ROLE_SALT, ROLE_NEUTRAL)

# The five tags the ChEBI submission template defines. Anything else in a record is
# reported, because the template is what their loader is configured for.
EXPECTED_TAGS = ("NAME", "SYNONYM", "IUPAC_NAME", "CAS_NO", "RELATIONSHIP")

# Synonym strings that are really component names, not names of the compound. They
# matter because the synonym delimiter is ";" with no space, so a bare component
# token is indistinguishable from a fragment of a split multi-part name.
COMPONENT_TOKENS = frozenset(
    {
        "hydrochloride",
        "hydrobromide",
        "dihydrochloride",
        "dihydrobromide",
        "trihydrochloride",
        "maleic acid",
        "fumaric acid",
        "(z)-but-2-enedioic acid",
        "(e)-but-2-enedioic acid",
        "oxalic acid",
        "methanesulfonic acid",
        "sulfuric acid",
        "hydroiodide",
        "hydrate",
        "sodium",
        "potassium",
        "4-methylbenzenesulfonic acid",
        "2,3-dihydroxybutanedioic acid",
        "(2r,3r)-2,3-dihydroxybutanedioic acid",
        "naphthalene-1,5-disulfonic acid",
        "ethanol",
        "chloride",
        "bromide",
        "iodide",
        "hydron",
    }
)

# Vendor and database catalogue identifiers, which are not names and should not be
# submitted as synonyms.
CATALOGUE_ID = re.compile(
    r"^(?:SCHEMBL\d+|CHEMBL\d+|DTX[SC]ID\d+|ZINC\d+|BDBM\d+|AKOS\d+|MFCD\d+|HMS\d+"
    r"|NCGC\d+|Tox21_\d+|CCG-\d+|NSC-?\d+|UNII-\w+|DB\d{5}|EN300-\d+|EX-A\d+|HY-\w+"
    r"|CS-\d+|s\d{4,}|SR-\d+|BRD-\w+|CAS-\d[\d-]+|Q\d{6,}|EU-\d+|BCP\d+|AC-\d+"
    r"|AB\d{5,}|SY\d{5,}|FT-\d+|AS-\d+|J-\d+|W-\d+|SMR\d+|MLS\d+|STK\d+|STL\d+"
    r"|LS-\d+|GTPL\d+|[CD]\d{5}|BIM-\d+|EINECS \d[\d-]+"
    r"|[A-Z]{1,4}-?\d{3,}[A-Z]?(?:-\d+)?)$",
    re.I,
)

# A structural identifier written where a name belongs. An InChIKey is 14 letters,
# a hyphen, 10 letters, a hyphen and one letter -- no digits anywhere -- so a
# "does it look like a word" test accepts it as a drug name. Matched explicitly
# instead.
INCHIKEY_SHAPED = re.compile(r"^[A-Z]{14}-[A-Z]{10}-[A-Z]$")

# A vendor code inside a name, stripped before stereo descriptors are looked for so
# that the "S" of "SB 203580" is not read as an (S) configuration.
VENDOR_CODE = re.compile(
    r"\b(?:RS|L|D|S|R|SR|SDZ|WAY|SB|PD|MRS|CGP|BMS|JNJ|GR|SKF|RU|RJR|TC|NNC|UK|ICI"
    r"|LY|CD|SN|SX|BIO|DS|CO|CH)[ -]?\d"
)

# A name asserting specific stereochemistry, and a name asserting a racemate or
# relative configuration. A name can match both, and then the racemate wins.
SPECIFIC = re.compile(
    r"\(\d*[RSEZ](?:,\d*[RSEZ])*\)|\((?:\+|-)\)"
    r"|\b(?:cis|trans|threo|erythro|exo|endo)\b|(?<![A-Za-z0-9-])[DL]-(?=[A-Za-z(])"
)
RACEMIC = re.compile(
    r"\(\+/-\)|\(\+-\)|\brac\b|\brel-|(?<![A-Za-z0-9])DL-|\(RS\)|\(R\*|\bracemic\b"
)

# Stoichiometry prefix in a salt name, and what each prefix claims.
SALT_WORD = re.compile(
    r"\b(hemi|sesqui|di|tri|tetra|mono)?(hydrochloride|hydrobromide|maleate"
    r"|fumarate|oxalate|iodide|bromide|chloride|sulfate|sulphate|tosylate|mesylate"
    r"|tartrate|napadisylate|sodium salt|potassium salt)"
)
PREFIX_COUNT = {
    None: 1,
    "mono": 1,
    "di": 2,
    "tri": 3,
    "tetra": 4,
    "hemi": 0.5,
    "sesqui": 1.5,
}

# Dibasic acids where both 1:1 and 2:1 are conventional, so a name with no prefix
# asserts nothing about the ratio.
AMBIGUOUS_RATIO_SALTS = ("napadisylate", "sulfate", "sulphate", "oxalate", "tartrate")


# A named solvate, with its optional multiplier prefix. Matched as a word rather
# than as a substring: "ethanol" appears inside ordinary compound names --
# 2-phenylethanol, aminoethanol, any alcohol whose parent chain is ethane -- and a
# substring test reports every one of them as an ethanolate with no ethanol drawn.
# The batch this was ported from happened to contain no such compound, so the
# prototype's `"ethanol" in iupac` never misfired; that is luck, not correctness.
# "hydrate" has the same problem in "dehydrate" and "carbohydrate".
_SOLVATE_PREFIX = r"(?:hemi|mono|di|tri|tetra|penta|hexa|hepta|octa|sesqui)?"
HYDRATE_WORD = re.compile(rf"(?<![a-z]){_SOLVATE_PREFIX}hydrate\b")
# Shared with SYN-04, which had the same bare-substring bug: it fired on a
# synonym reading "carbohydrate derivative" or "sodium dehydrate".
ETHANOLATE_WORD = re.compile(rf"(?<![a-z]){_SOLVATE_PREFIX}ethanolate\b")

# A solvate can also arrive as a standalone component of a PubChem machine name,
# which joins components with ";" and no space.
HYDRATE_COMPONENTS = frozenset({"hydrate", "water", "oxidane"})
ETHANOLATE_COMPONENTS = frozenset({"ethanol"})

IUPAC_HCL = re.compile(r"(di|tri|tetra)?hydrochloride")
IUPAC_STEREO = re.compile(r"\(\d*[rs](?:,\d*[rs])*\)")
NAME_ANNOTATION = re.compile(
    r"\((?:[^()]*(?:inhibitor|NSC|antagonist|agonist)[^()]*)\)"
)
NAME_COMMA_SALT = re.compile(r", (sodium|potassium) salt")
NAME_SHORT_ALPHA = re.compile(r"\b[a]-[A-Z]")

# The synonym delimiter is ";" with no surrounding space: 194 of the 195 original
# salt records use exactly that, and '"; "' trips the whitespace check.
SYNONYM_DELIMITER = ";"


@dataclass(frozen=True)
class Check:
    """What one check is, independent of any record it runs against."""

    id: str
    title: str
    independent: bool
    severities: tuple[str, ...]


@dataclass(frozen=True)
class Finding:
    """One check's verdict on one record.

    ``cas`` is the join key to waivers, quarantine and the reference tables.
    ``name`` is display text only and must never be joined on.
    """

    check: str
    severity: str
    detail: str
    cas: str = ""
    name: str = ""
    record_index: int = 0
    evidence: str = ""
    independent: bool | None = None
    waiver: str | None = None

    @property
    def is_independent(self) -> bool:
        """Whether this finding compared sources of different origin."""
        if self.independent is not None:
            return self.independent
        return CHECKS[self.check].independent


CHECKS: dict[str, Check] = {}
_RECORD_CHECKS: list[tuple[str, Callable[[RecordContext], Iterator[Finding]]]] = []
_FILE_CHECKS: list[tuple[str, Callable[[FileContext], Iterator[Finding]]]] = []


def _register(
    check_id: str,
    title: str,
    *,
    independent: bool,
    severities: tuple[str, ...],
    scope: str = "record",
) -> Callable[[Callable], Callable]:
    """Declare a check and add its function to the registry."""

    def decorate(func: Callable) -> Callable:
        if check_id in CHECKS:
            raise ValueError(f"check {check_id} is already registered")
        CHECKS[check_id] = Check(
            id=check_id, title=title, independent=independent, severities=severities
        )
        if scope == "record":
            _RECORD_CHECKS.append((check_id, func))
        elif scope == "file":
            _FILE_CHECKS.append((check_id, func))
        elif scope != "declared":
            raise ValueError(f"unknown check scope {scope!r}")
        return func

    return decorate


@dataclass
class RecordContext:
    """One record and everything derived from it that more than one check needs."""

    record: SdfRecord
    structure: Structure
    role: str = ROLE_AUTO

    def __post_init__(self) -> None:
        data = self.record.data
        self.name = self.record.name
        self.cas = self.record.cas
        self.relationship = data.get("RELATIONSHIP", "").strip()
        self.synonym = data.get("SYNONYM")
        self.iupac = data.get("IUPAC_NAME") or ""
        self.name_lower = self.name.lower()
        self.iupac_lower = self.iupac.lower()
        # Vendor code stripped first, so "RS 56812" does not read as (RS).
        cleaned = VENDOR_CODE.sub("", self.name)
        self.specific = bool(SPECIFIC.search(cleaned))
        self.racemic = bool(RACEMIC.search(cleaned))
        self.is_salt = self._resolve_is_salt()

    def _resolve_is_salt(self) -> bool:
        """Whether salt-only checks apply to this record.

        A single input file carries no group context, so by default each record is
        judged on what it is: more than one fragment, or an asserted class. The
        explicit roles exist to reproduce the original two-file behaviour, where one
        file was known to hold salts and the other known not to.

        Deliberately broader than :attr:`has_counterion`: this answers "is this a
        multi-component record", which is the right question for a stoichiometry
        check or a has-part link, and a hydrate is one of those. It is the wrong
        question for "must this record name a class", which is what
        :attr:`has_counterion` is for.
        """
        if self.role == ROLE_SALT:
            return True
        if self.role == ROLE_NEUTRAL:
            return False
        return self.structure.n_frag > 1 or bool(self.relationship)

    @property
    def has_counterion(self) -> bool:
        """Whether a fragment beyond the parent is something other than solvate.

        Solvent of crystallisation is not a counterion, and the class table has no
        code for a hydrate or an ethanolate -- every entry in it names an ion. So a
        record that is a parent plus water has no class it *could* assert, and
        demanding one held it back at ``high`` with no value that would release it.
        A held record is supposed to have a route out.

        Reading the fragments rather than ``is_salt`` also keeps this honest under
        ``--role salt``: the role says which checks apply to the file, not that
        every record in it grew a counterion.
        """
        return any(x not in classes.SOLVATES for x in self.structure.counter)

    @property
    def cas_key(self) -> str:
        """The CAS number normalised, for joining to decisions and reference data.

        Separate from :attr:`cas`, which is the raw string as the file spells it,
        because two orthogonal things were being conflated. INT-04 must complain
        about the *string* -- ``0557-66-4`` is not a CAS Registry Number and ChEBI
        would store it verbatim. A waiver or a quarantine row is about the
        *compound*, and must keep applying while that spelling is being fixed.
        Joining on the raw string meant a record could not match its own decision,
        and the run then reported "matches no record" while the record was sitting
        right there.
        """
        if not self.cas:
            return ""
        from cas_registry import CAS_VALID, classify_cas

        normalised, verdict, _ = classify_cas(self.cas)
        return normalised if verdict == CAS_VALID else self.cas

    def finding(self, check: str, severity: str, detail: str, **kw) -> Finding:
        return Finding(
            check=check,
            severity=severity,
            detail=detail,
            cas=self.cas,
            name=self.name,
            record_index=self.record.index,
            **kw,
        )


@dataclass
class FileContext:
    """Every record in one file, for the checks that compare records with each other."""

    contexts: list[RecordContext]
    raw: bytes


# ------------------------------------------------------------- record integrity


@_register(
    "INT-02",
    "Record structure matches the submission template",
    independent=True,
    severities=(MEDIUM,),
)
def int02_template_shape(ctx: RecordContext) -> Iterator[Finding]:
    record = ctx.record
    if record.title != record.data.get("NAME", ""):
        # Handoff case 15: a rename has to update the molfile title line too, or
        # the record that was just fixed fails this check.
        yield ctx.finding("INT-02", MEDIUM, "mol title differs from NAME")
    extra = [t for t in record.tag_order if t not in EXPECTED_TAGS]
    if extra:
        yield ctx.finding("INT-02", MEDIUM, f"unexpected tags {extra}")
    for tag, value in record.data.items():
        if "\n" in value.strip():
            yield ctx.finding("INT-02", MEDIUM, f"{tag} spans several lines")


@_register(
    "INT-03",
    "Required fields are present and non-empty",
    independent=True,
    severities=(HIGH, MEDIUM),
)
def int03_required_fields(ctx: RecordContext) -> Iterator[Finding]:
    data = ctx.record.data
    for tag in ("NAME", "CAS_NO"):
        if not data.get(tag, "").strip():
            yield ctx.finding("INT-03", HIGH, f"{tag} missing or empty")
    for tag in ("SYNONYM", "IUPAC_NAME"):
        if tag not in data:
            yield ctx.finding("INT-03", MEDIUM, f"{tag} absent")
    if ctx.has_counterion and not ctx.relationship:
        yield ctx.finding(
            "INT-03", HIGH, "salt record with no RELATIONSHIP class asserted"
        )


@_register(
    "INT-04",
    "CAS Registry Number is well formed and its check digit verifies",
    independent=True,
    severities=(HIGH,),
)
def int04_cas_number(ctx: RecordContext) -> Iterator[Finding]:
    """CAS check-digit arithmetic, one of the few checks that owes nothing to a source.

    Delegates to bcp/cas_registry.py, which already carries this repo's CAS
    handling and its tests, rather than keeping a second copy of the arithmetic.
    That module knows failure modes the prototype's four-line ``cas_status`` did
    not: unicode dash mojibake, a value Excel turned into a date, a leading zero,
    a zero-padded check digit, rotated segments.

    But it *classifies for repair*, and this gate must not accept a repairable
    value. ``classify_cas("42971-09-05")`` returns verdict ``valid`` with repair
    ``zero_padded_check_digit``, because the intended number is recoverable. The
    string in the file is still not a CAS Registry Number, and the string in the
    file is what ChEBI would store. So a non-empty repair code is a high finding
    naming the repair, which is also the fix instruction.
    """
    from cas_registry import (
        CAS_INVALID_CHECKSUM,
        CAS_INVALID_FORMAT,
        CAS_MISSING,
        classify_cas,
    )

    raw = ctx.record.data.get("CAS_NO", "")
    normalised, verdict, repair = classify_cas(raw)
    if verdict == CAS_MISSING:
        # INT-03 already reports an absent or empty CAS; saying it twice adds
        # nothing to the record's report and doubles its finding count.
        return
    if verdict == CAS_INVALID_FORMAT:
        yield ctx.finding("INT-04", HIGH, f"CAS {raw!r}: not a CAS Registry Number")
    elif verdict == CAS_INVALID_CHECKSUM:
        yield ctx.finding("INT-04", HIGH, f"CAS {raw}: check digit does not verify")
    elif repair:
        yield ctx.finding(
            "INT-04",
            HIGH,
            f"CAS {raw!r} is malformed ({repair}); the well-formed value is "
            f"{normalised}",
        )


@_register(
    "INT-07",
    "Molfile parses and is a V2000 connection table",
    independent=True,
    severities=(HIGH,),
)
def int07_molfile(ctx: RecordContext) -> Iterator[Finding]:
    if not ctx.structure.parse:
        yield ctx.finding("INT-07", HIGH, "mol block does not parse")
        return
    if "V2000" not in ctx.record.counts_line:
        yield ctx.finding("INT-07", HIGH, "counts line lacks V2000")


@_register(
    "INT-08",
    "Structure carries a two-dimensional drawing",
    independent=True,
    severities=(MEDIUM,),
)
def int08_coordinates(ctx: RecordContext) -> Iterator[Finding]:
    if ctx.structure.parse and ctx.structure.zero_coords:
        yield ctx.finding("INT-08", MEDIUM, "all coordinates zero")


@_register(
    "INT-09",
    "Structure is electrically neutral overall",
    independent=True,
    severities=(HIGH,),
)
def int09_net_charge(ctx: RecordContext) -> Iterator[Finding]:
    if ctx.structure.parse and ctx.structure.net_charge != 0:
        yield ctx.finding(
            "INT-09",
            HIGH,
            f"net charge {ctx.structure.net_charge} with no counterion, "
            "or ion named as neutral",
        )


# ------------------------------------------------- name against drawn structure


@_register(
    "CON-01",
    "Asserted ChEBI class is supported by the counterions drawn",
    independent=True,
    severities=(HIGH,),
)
def con01_class_supported(ctx: RecordContext) -> Iterator[Finding]:
    if not ctx.relationship or not ctx.structure.parse:
        return
    name = classes.class_name(ctx.relationship)
    if name is None:
        yield ctx.finding(
            "CON-01",
            HIGH,
            f"unknown or unverified relationship {ctx.relationship}",
        )
        return
    if classes.class_supported(name, ctx.structure):
        return
    reason = classes.unsupported_reason(name, ctx.structure)
    # A maleate or fumarate whose double bond is undefined is a distinct problem
    # from a class contradicted by the structure: the evidence is missing rather
    # than wrong, and it is fixed by specifying the bond.
    undefined_geometry = name in ("maleate", "fumarate") and (
        "undefined" in ctx.structure.geoms
    )
    check = "CON-05" if undefined_geometry else "CON-01"
    yield ctx.finding(check, HIGH, f"class {name} not supported by structure: {reason}")


@_register(
    "CON-05",
    "Butenedioate double-bond geometry is specified, so maleate and fumarate differ",
    independent=True,
    severities=(HIGH,),
    scope="declared",
)
def con05_declared() -> None:
    """Emitted by :func:`con01_class_supported`, declared here so it has metadata.

    CON-05 is the same comparison as CON-01 with a different remedy -- the geometry
    is missing rather than contradicted, so the fix is to specify the bond, not to
    change the asserted class. Doing the class lookup twice in two functions is
    how the two drift apart, so one function emits both IDs.
    """


@_register(
    "CON-02",
    "Stoichiometry prefix in the name matches the counterions drawn",
    independent=True,
    severities=(HIGH,),
)
def con02_stoichiometry_word(ctx: RecordContext) -> Iterator[Finding]:
    if not ctx.structure.parse:
        return
    match = SALT_WORD.search(ctx.name_lower)
    if not match or not (ctx.is_salt or match.group(1)):
        return

    prefix = match.group(1)
    frags = ctx.structure.frags
    # The denominator is every fragment that is neither a counterion nor solvent of
    # crystallisation, counted. Two things made the old `base_counts[0]` wrong, and
    # both changed the answer rather than merely the wording. `frags` is keyed in
    # RDKit fragment order, so "the base" was whichever such fragment was drawn
    # first: decane-1,10-diamine dihydrochloride dihydrate divides by 1 or by 2
    # depending only on whether its waters precede its amine in the molfile, and
    # the water-first drawing reports "di implies 2, structure has 1" on a record
    # whose stoichiometry is exactly right. Water and ethanol were in the
    # denominator at all for the same reason -- they are not counterions, so they
    # read as base. Whether a solvate is present is CON-03's question, and it has
    # no business changing a counterion ratio.
    #
    # Summing rather than taking the parent's count is deliberate: the parent is
    # the fragment with the most heavy atoms, and 3-Methyl-GABA napadisylate is a
    # small base against a naphthalenedisulfonate half again its size, so the
    # "parent" there is the counterion. Summing keeps the 2:1 that makes its
    # ratio 0.5, and keeps a doubled base -- a hemifumarate is drawn 2:1 -- for the
    # same reason.
    # `classes.is_counterion` is the single table. CON-02 used to keep a second
    # one, which listed the neutral acid of every organic counterion and almost
    # none of the anions, so an ionically drawn salt counted its counterion as base
    # and this check reported a wrong ratio on a correct record.
    salt_n = sum(v for k, v in frags.items() if classes.is_counterion(k))
    base_n = sum(
        v
        for k, v in frags.items()
        if not classes.is_counterion(k) and k not in classes.SOLVATES
    )
    ratio = salt_n / base_n if base_n else None

    want = PREFIX_COUNT[prefix]
    class_name = classes.class_name(ctx.relationship) if ctx.relationship else None
    if class_name in ("sodium", "potassium") and prefix is None:
        # "tetrasodium salt" puts the count before the word this regex matched, so
        # a missing prefix here asserts nothing.
        want = None
    if prefix is None and match.group(2) in AMBIGUOUS_RATIO_SALTS and ratio in (0.5, 1):
        want = ratio

    if want is not None and ratio is not None and abs(ratio - want) > 1e-6:
        yield ctx.finding(
            "CON-02",
            HIGH,
            f'name prefix "{prefix or "mono"}" implies {want} counterion(s) '
            f"per base, structure has {ratio:g} ({frags})",
        )


@_register(
    "CON-03",
    "Solvate named in the name is present in the structure",
    independent=True,
    severities=(HIGH,),
)
def con03_solvates(ctx: RecordContext) -> Iterator[Finding]:
    if not ctx.structure.parse:
        return
    # Only a genuine component list is solvate evidence. An IUPAC name that is
    # exactly "ethanol" describes ethanol, not an ethanolate of something else.
    components = (
        {c.strip().lower() for c in ctx.iupac.split(";")} if ";" in ctx.iupac else set()
    )

    names_hydrate = (
        HYDRATE_WORD.search(ctx.name_lower)
        or HYDRATE_WORD.search(ctx.iupac_lower)
        or bool(components & HYDRATE_COMPONENTS)
    )
    if names_hydrate and not ctx.structure.water:
        yield ctx.finding("CON-03", HIGH, "name says hydrate, no water in structure")

    names_ethanolate = (
        ETHANOLATE_WORD.search(ctx.name_lower)
        or ETHANOLATE_WORD.search(ctx.iupac_lower)
        or bool(components & ETHANOLATE_COMPONENTS)
    )
    if names_ethanolate and not ctx.structure.ethanol:
        yield ctx.finding(
            "CON-03", HIGH, "name says ethanolate, no ethanol in structure"
        )


@_register(
    "CON-04",
    "Stereochemistry asserted by the name matches the structure",
    independent=True,
    severities=(HIGH, MEDIUM),
)
def con04_stereochemistry(ctx: RecordContext) -> Iterator[Finding]:
    s = ctx.structure
    if not s.parse:
        return
    if ctx.racemic and s.stereo_total and s.stereo_unspec == 0:
        yield ctx.finding(
            "CON-04", HIGH, "name says racemate/relative, structure fully specified"
        )
    if ctx.specific and not ctx.racemic and s.stereo_unspec:
        yield ctx.finding(
            "CON-04",
            MEDIUM,
            f"name is stereospecific, {s.stereo_unspec}/{s.stereo_total} "
            "stereo elements unspecified",
        )
    elif not ctx.racemic and s.stereo_unspec and IUPAC_STEREO.search(ctx.iupac_lower):
        yield ctx.finding(
            "CON-04",
            MEDIUM,
            f"IUPAC name carries R/S descriptors but {s.stereo_unspec}/"
            f"{s.stereo_total} stereo elements are unspecified in the structure",
        )


@_register(
    "CON-09",
    "Chiral flag agrees with an enantiopure drawing",
    independent=True,
    severities=(LOW,),
)
def con09_chiral_flag(ctx: RecordContext) -> Iterator[Finding]:
    s = ctx.structure
    if not s.parse:
        return
    if (
        ctx.specific
        and not ctx.racemic
        and s.tetra_specified
        and s.stereo_unspec == 0
        and s.chiral_flag != 1
    ):
        yield ctx.finding(
            "CON-09",
            LOW,
            "enantiopure structure but chiral flag 0 "
            "(relative stereo by MDL convention)",
        )


@_register(
    "CON-07",
    "Salt and non-salt records carry the fields their kind requires",
    independent=True,
    severities=(HIGH, MEDIUM),
)
def con07_role_consistency(ctx: RecordContext) -> Iterator[Finding]:
    if not ctx.is_salt and ctx.relationship:
        yield ctx.finding("CON-07", MEDIUM, "non-salt record carries a RELATIONSHIP")
    if ctx.role == ROLE_NEUTRAL and ctx.structure.n_frag > 1:
        yield ctx.finding(
            "CON-07",
            HIGH,
            f"multi-fragment structure in a neutral file: {ctx.structure.frags}",
        )


@_register(
    "CON-08",
    "Stoichiometry in the systematic name matches the structure",
    independent=True,
    severities=(HIGH,),
)
def con08_iupac_stoichiometry(ctx: RecordContext) -> Iterator[Finding]:
    if not ctx.structure.parse or not ctx.iupac:
        return
    if not (ctx.is_salt or ctx.role == ROLE_SALT):
        return
    match = IUPAC_HCL.search(ctx.iupac_lower)
    if not match:
        return
    drawn = sum(v for k, v in ctx.structure.frags.items() if k in ("HCl", "Cl-"))
    want = {"di": 2, "tri": 3, "tetra": 4}.get(match.group(1), 1)
    if drawn != want:
        yield ctx.finding(
            "CON-08",
            HIGH,
            f'IUPAC "{match.group(0)}" vs {drawn} HCl in structure',
        )


@_register(
    "CON-10",
    "Name is a chemical name, formatted as ChEBI expects",
    independent=True,
    severities=(HIGH, MEDIUM, LOW),
)
def con10_name_formatting(ctx: RecordContext) -> Iterator[Finding]:
    name = ctx.name
    if NAME_ANNOTATION.search(name):
        yield ctx.finding("CON-10", MEDIUM, "annotation in parentheses inside NAME")
    if NAME_COMMA_SALT.search(name):
        yield ctx.finding("CON-10", LOW, "comma-style salt suffix in NAME")
    if NAME_SHORT_ALPHA.search(name):
        yield ctx.finding("CON-10", LOW, '"a-" used where "alpha-" intended')
    if re.fullmatch(r"PMPA.*", name):
        yield ctx.finding(
            "CON-10", HIGH, "PMPA is ambiguous (also tenofovir); use 2-PMPA"
        )


# -------------------------------------------------------------- synonym hygiene


@_register(
    "SYN-01",
    "Synonyms are names, not catalogue identifiers",
    independent=True,
    severities=(MEDIUM,),
)
def syn01_catalogue_ids(ctx: RecordContext) -> Iterator[Finding]:
    items = _synonyms(ctx)
    if items is None:
        return
    ids = [i for i in items if CATALOGUE_ID.match(i)]
    if ids:
        yield ctx.finding(
            "SYN-01",
            MEDIUM,
            f"{len(ids)} catalogue/database identifiers: {ids[:5]}",
        )


@_register(
    "SYN-02",
    "No bare component token, which the delimiter cannot be told from a name part",
    independent=True,
    severities=(MEDIUM,),
)
def syn02_component_tokens(ctx: RecordContext) -> Iterator[Finding]:
    items = _synonyms(ctx)
    if items is None:
        return
    bare = [i.lower() for i in items if i.lower() in COMPONENT_TOKENS]
    if bare:
        yield ctx.finding(
            "SYN-02", MEDIUM, f"bare component tokens (delimiter collision): {bare}"
        )


@_register(
    "SYN-03",
    "Synonyms are not case or spacing duplicates of each other",
    independent=True,
    severities=(LOW,),
)
def syn03_near_duplicates(ctx: RecordContext) -> Iterator[Finding]:
    items = _synonyms(ctx)
    if items is None:
        return
    lowered = [i.lower() for i in items]
    squashed = {re.sub(r"[\s\-,]", "", i) for i in lowered}
    if len(squashed) < len(lowered):
        yield ctx.finding("SYN-03", LOW, "case/spacing duplicates")


@_register(
    "SYN-04",
    "Synonyms do not contradict the entry's stereochemistry or solvation",
    independent=True,
    severities=(MEDIUM,),
)
def syn04_contradictions(ctx: RecordContext) -> Iterator[Finding]:
    items = _synonyms(ctx)
    if items is None:
        return
    if ctx.specific and not ctx.racemic and any(RACEMIC.search(i) for i in items):
        yield ctx.finding(
            "SYN-04", MEDIUM, "racemic/rel synonyms on an enantiopure entry"
        )
    # `parse` gates the structural half, and only that half: the racemic clause
    # above compares two names and is answerable without a structure. Structure's
    # own docstring says its defaults mean "unknown", not "absent", so reading
    # `water` on a record RDKit could not read calls it anhydrous on no evidence --
    # the record is held by INT-07 either way, but its report then carries a claim
    # the gate never established, and that report is what a chemist works from.
    if (
        ctx.structure.parse
        and not ctx.structure.water
        and any(HYDRATE_WORD.search(i.lower()) for i in items)
    ):
        yield ctx.finding("SYN-04", MEDIUM, "hydrate synonyms on an anhydrous entry")


@_register(
    "SYN-05",
    "Synonym list uses the bare ';' delimiter with no stray whitespace",
    independent=True,
    severities=(LOW,),
)
def syn05_whitespace(ctx: RecordContext) -> Iterator[Finding]:
    if ctx.synonym is None:
        return
    parts = ctx.synonym.split(SYNONYM_DELIMITER)
    if any(p != p.strip() or "  " in p for p in parts):
        yield ctx.finding("SYN-05", LOW, "whitespace oddities")


@_register(
    "SYN-06",
    "Synonyms are not structural identifiers",
    independent=True,
    severities=(MEDIUM,),
)
def syn06_structural_identifiers(ctx: RecordContext) -> Iterator[Finding]:
    """An InChIKey has no digits, so a "looks like a word" filter accepts it.

    Handoff case 14: 42 candidate drug names became 10 once identifiers of this
    shape were excluded, of which 6 were real.
    """
    items = _synonyms(ctx)
    if items is None:
        return
    bad = [i for i in items if INCHIKEY_SHAPED.match(i) or i.startswith("InChI=")]
    if bad:
        yield ctx.finding(
            "SYN-06", MEDIUM, f"structural identifiers as synonyms: {bad[:3]}"
        )


@_register(
    "IUP-01",
    "Systematic name is a name, not a machine-joined component list",
    independent=True,
    severities=(LOW,),
)
def iup01_machine_name(ctx: RecordContext) -> Iterator[Finding]:
    if ctx.iupac and ";" in ctx.iupac:
        yield ctx.finding(
            "IUP-01", LOW, "PubChem machine name (semicolon-joined components)"
        )


def _synonyms(ctx: RecordContext) -> list[str] | None:
    """The synonym list, or None when the field is absent.

    Absent and empty are different: INT-03 reports an absent SYNONYM, and the
    hygiene checks have nothing to say about it.
    """
    if ctx.synonym is None:
        return None
    return [i.strip() for i in ctx.synonym.split(SYNONYM_DELIMITER)]


# ------------------------------------------------------------- whole-file checks


@_register(
    "INT-06",
    "File is ASCII with Unix line endings",
    independent=True,
    severities=(HIGH, LOW),
    scope="file",
)
def int06_file_encoding(fctx: FileContext) -> Iterator[Finding]:
    """Attributed to the file, not to a record, so it is reported once.

    The prototype appended these to every record's finding list, which multiplied
    one file-level problem by the record count and held back all 290 records for a
    single stray byte.
    """
    if any(b > 127 for b in fctx.raw):
        yield Finding(
            check="INT-06", severity=HIGH, detail="file contains non-ASCII bytes"
        )
    if b"\r" in fctx.raw:
        yield Finding(check="INT-06", severity=LOW, detail="file has CRLF line endings")


@_register(
    "INT-05",
    "No two records are the same compound",
    independent=True,
    severities=(HIGH,),
    scope="file",
)
def int05_duplicates(fctx: FileContext) -> Iterator[Finding]:
    """Duplicate CAS, name or structure, attributed to every record involved.

    Reported per record rather than once per group so that holding back a record
    is enough to act on it. Records are identified by CAS in the message, because
    a name-keyed message goes stale the moment one of the pair is renamed.
    """
    keys: tuple[tuple[str, Callable[[RecordContext], str | None]], ...] = (
        ("CAS", lambda c: c.cas or None),
        ("NAME", lambda c: c.name.lower() or None),
        ("InChIKey", lambda c: c.structure.inchikey),
    )
    for label, getter in keys:
        groups: dict[str, list[RecordContext]] = defaultdict(list)
        for ctx in fctx.contexts:
            value = getter(ctx)
            if value:
                groups[value].append(ctx)
        for value, members in groups.items():
            if len(members) < 2:
                continue
            for ctx in members:
                others = [
                    f"{o.cas or 'no CAS'} ({o.name})" for o in members if o is not ctx
                ]
                yield ctx.finding(
                    "INT-05",
                    HIGH,
                    f"duplicate {label} {value!r} shared with {others}",
                )


@_register(
    "REL-01",
    "Records sharing a parent skeleton, as relationship candidates",
    independent=True,
    severities=(INFO,),
    scope="file",
)
def rel01_shared_parents(fctx: FileContext) -> Iterator[Finding]:
    """Never holds a record back; it tells a curator which links to consider."""
    groups: dict[str, list[RecordContext]] = defaultdict(list)
    for ctx in fctx.contexts:
        skeleton = ctx.structure.parent_skeleton
        if skeleton:
            groups[skeleton].append(ctx)
    for members in groups.values():
        if len(members) < 2:
            continue
        for ctx in members:
            others = [
                f"{o.cas or 'no CAS'} ({o.name})" for o in members if o is not ctx
            ]
            yield ctx.finding(
                "REL-01",
                INFO,
                f"shares a parent skeleton with {others}; candidate "
                "is-enantiomer-of / has-part relationship",
            )


@_register(
    "EXT-01",
    "CAS Registry Number resolves to the structure that was drawn",
    independent=False,
    severities=(HIGH, MEDIUM, LOW),
    scope="declared",
)
def ext01_declared() -> None:
    """Emitted by the external-check layer once a reference cache is available.

    Declared ``independent=False`` on purpose: the submission SDFs were generated
    from PubChem, so a PubChem-resolved finding is a source confirming itself and
    must not be counted as independent evidence. The layer sets
    ``independent=True`` on the findings it resolves through the CAS registry
    export, which is a human-supplied artifact of a different origin. Defaulting
    the other way would silently inflate the independent count.
    """


@_register(
    "EXT-02",
    "Structure is not already present in ChEBI",
    independent=True,
    severities=(HIGH, LOW),
    scope="declared",
)
def ext02_declared() -> None:
    """High for an exact match to an existing entry: that is a duplicate submission.

    Low for a skeleton match. It is explicitly *not* a duplicate -- a different
    stereoisomer or salt form of something ChEBI holds -- so it must not hold a
    submission; it tells a curator which relationship to state. It was medium
    until the severities were checked against what the batch does: 38 of the 283
    records already deposited would have been held by it under the default
    policy, every one for having a relative rather than a defect.

    There is no merged-entry severity, because there is no merged-entry case.
    Handoff case 9 says a merged entry must not trigger removal and that liveness
    comes from ``parent_id`` in compounds.tsv; that mechanism does not exist --
    ``parent_id`` is non-empty in 0 of 218,533 rows, and the real merge pointer is
    secondary_ids.tsv. The question is moot for structure matching either way: all
    189,896 structure-bearing compound ids are primary and none is a secondary, so
    a structure match can never land on a merged entry. See
    :mod:`chebi_gate.chebi_release`.
    """


@_register(
    "EXT-03",
    "Parent compound already in ChEBI, so a has-part link is available",
    independent=True,
    severities=(INFO,),
    scope="declared",
)
def ext03_declared() -> None:
    """Never holds a record; it tells a curator which link to add.

    Only an exact parent-key match counts. Accepting skeleton matches here took
    this from 165 candidates to 206 and changed what it meant.
    """


@_register(
    "EXT-04",
    "CAS registry formula agrees with the stoichiometry drawn",
    independent=True,
    severities=(HIGH, MEDIUM, LOW, INFO),
    scope="declared",
)
def ext04_declared() -> None:
    """The only stoichiometry evidence whose origin is not the SDF generation step.

    Four severities, one per status the comparison can reach:

    high
        ``DISAGREE`` -- the registry and the drawing differ in something other
        than hydrogen count. 3 of 290 on the reference batch.
    medium
        ``ratio-unknown-to-CAS`` -- the registry itself declines to fix the
        component ratio, so a name asserting one cannot be confirmed. 3 of 290.
    low
        ``no-registry-record`` -- there is no registry row for this CAS, so the
        record cannot be checked on this axis and the report must say so rather
        than imply it passed.
    info
        ``convention`` -- differs by hydrogen only, which is a neutral acid
        registered against an ionically drawn salt. 10 of 290, not a defect.
    """


@_register(
    "QUAR-01",
    "Record has an open question recorded against it in the decisions data",
    independent=True,
    severities=(HIGH,),
    scope="declared",
)
def quar01_declared() -> None:
    """Emitted by the decisions layer, not by inspecting the record.

    An open question is a reason to hold a record that no amount of looking at the
    record will reveal -- "which salt does the lab actually hold?" is answered by
    the lab, not by the file. Recording it as a finding is what makes it visible
    in the report and what makes resolving it a data edit rather than a code edit.
    """


# ------------------------------------------------------------------------ runner


def run_record_checks(ctx: RecordContext) -> list[Finding]:
    """Every record-scoped finding for one record."""
    out: list[Finding] = []
    for check_id, func in _RECORD_CHECKS:
        for finding in func(ctx):
            out.append(validate_finding(finding, check_id))
    return out


def run_file_checks(fctx: FileContext) -> list[Finding]:
    """Every file-scoped finding: duplicates, encoding, shared parents."""
    out: list[Finding] = []
    for check_id, func in _FILE_CHECKS:
        for finding in func(fctx):
            out.append(validate_finding(finding, check_id))
    return out


def validate_finding(finding: Finding, emitting_check: str) -> Finding:
    """Assert a finding matches what its check declared it could emit.

    A check that emits a severity it never declared is a bug in the check, and one
    that silently escapes turns into a record cleared or held for a reason nobody
    can look up. CON-01 legitimately emits CON-05, so the emitting function and
    the finding's check ID are allowed to differ.
    """
    check = CHECKS.get(finding.check)
    if check is None:
        raise ValueError(
            f"{emitting_check} emitted a finding for unregistered check "
            f"{finding.check!r}"
        )
    if finding.waiver is not None and finding.severity == INFO:
        # A waiver downgrades to info after validation; re-validating a waived
        # finding must not reject it for a severity its check never declares.
        return finding
    if finding.severity not in check.severities:
        raise ValueError(
            f"{finding.check} emitted severity {finding.severity!r}, "
            f"declared {check.severities}"
        )
    return finding


def worst_severity(findings: list[Finding]) -> str | None:
    """The most serious severity among findings, or None when there are none."""
    if not findings:
        return None
    return min((f.severity for f in findings), key=lambda s: SEVERITY_RANK[s])


def waive(finding: Finding, reason: str, evidence: str) -> Finding:
    """Downgrade a finding to info, keeping it visible with its reason attached.

    A waiver is a written decision that a finding is correct as it stands, so it
    must not hide the finding: the record still reports it, at info level, with the
    reason and evidence that justified the decision.
    """
    return replace(
        finding,
        severity=INFO,
        detail=f"{finding.detail} [WAIVED: {reason}]",
        evidence=evidence or finding.evidence,
        waiver=reason,
    )
