"""Checks that compare a record against evidence from outside the file.

The single most important idea in the gate lives here. The submission SDFs were
generated by asking PubChem about each CAS number, so checking those SDFs against
PubChem is asking a source to confirm itself. On the reference batch that check
passed 284 of 290 records, and the number means almost nothing -- it mostly says
the generation step ran. Checked against evidence of a different origin, the same
batch showed efonidipine missing an ethanol fragment the circular check had called
flawless.

So every finding records whether its evidence was independent, and sources are
consulted worst-last:

1. the parsed SciFinder export -- independent, a versioned human artifact, and the
   only source with a row for all 290 records
2. CAS Common Chemistry -- independent, but thin: 82 of 291 cached numbers resolve
3. the PubChem cache -- circular, and used only when nothing else can speak

Two traps this layer exists to avoid, both of which produce a clean report:

**A transient failure is not a negative.** The caches persist ``cids_status``,
``property_status`` and ``http_status``, but nothing in the prototype ever read
them, so "PubChem has no such compound" and "PubChem was down for eight seconds"
were byte-for-byte indistinguishable and both came out as ``unresolved``. One
record was falsely unresolved that way. Here a non-200 cached response is its own
status, ``unavailable``, which says re-fetch rather than asserting a negative --
and it outranks ``unresolved`` so a real negative never masks an unknown.

**A CAS number resolving to several PubChem records must not be judged on the
first.** 22 of 290 resolved to more than one CID and one to eighteen. Judging
whichever came back first invented three stereo mismatches and seven wrong salt
forms, so every cached candidate is evaluated and the best-ranked one wins.
"""

from __future__ import annotations

import json
import logging
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path

from . import formula as formula_mod
from .casreg import EMPTY as EMPTY_REGISTRY
from .casreg import Registry
from .chebi_release import EMPTY as EMPTY_INDEX
from .chebi_release import Index
from .checks import HIGH, INFO, LOW, MEDIUM, Finding, RecordContext

log = logging.getLogger(__name__)

EXACT = "exact"
SKELETON = "skeleton"
PARENT_ONLY = "parent-only"
MISMATCH = "mismatch"
UNAVAILABLE = "unavailable"
UNRESOLVED = "unresolved"

# Lower is a more informative answer. `unavailable` deliberately outranks
# `unresolved`: if one source could not be reached and another returned nothing,
# the honest combined verdict is "we do not know", not "it does not exist".
RANK = {
    EXACT: 0,
    SKELETON: 1,
    PARENT_ONLY: 2,
    MISMATCH: 3,
    UNAVAILABLE: 4,
    UNRESOLVED: 5,
}

# The PubChem property key for an isomeric SMILES. PubChem renamed
# IsomericSMILES to SMILES in 2025 and still accepts the old name, returning HTTP
# 200 keyed by the new one -- so a fetcher that retries only on HTTP 400 never
# retries, and a consumer reading the old key silently gets nothing. All 291
# cached records carry SMILES and none carries IsomericSMILES. Read every spelling.
SMILES_KEYS = ("SMILES", "IsomericSMILES", "ConnectivitySMILES", "CanonicalSMILES")

REGISTRY_SOURCE = "CAS registry export"
COMMON_CHEMISTRY_SOURCE = "CAS Common Chemistry"
PUBCHEM_SOURCE = "PubChem"


@dataclass(frozen=True)
class Candidate:
    """One outside claim about what a CAS number denotes."""

    source: str
    independent: bool
    inchikey: str | None = None
    formula: str | None = None
    name: str = ""
    url: str = ""
    available: bool = True
    detail: str = ""

    @property
    def label(self) -> str:
        return f"{self.source}{f' ({self.detail})' if self.detail else ''}"


@dataclass(frozen=True)
class Verdict:
    """What the outside sources collectively say about one record."""

    status: str
    candidate: Candidate | None
    independent: bool
    note: str = ""


@dataclass(frozen=True)
class Evidence:
    """Every reference source a run has available. All optional."""

    registry: Registry = EMPTY_REGISTRY
    chebi: Index = EMPTY_INDEX
    pubchem_dir: Path | None = None
    common_chemistry_dir: Path | None = None

    @property
    def available(self) -> tuple[str, ...]:
        """Which sources this run can actually consult, for the summary."""
        out = []
        if len(self.registry):
            out.append(REGISTRY_SOURCE)
        if self.common_chemistry_dir and self.common_chemistry_dir.is_dir():
            out.append(COMMON_CHEMISTRY_SOURCE)
        if self.pubchem_dir and self.pubchem_dir.is_dir():
            out.append(PUBCHEM_SOURCE)
        if len(self.chebi):
            out.append("ChEBI release")
        return tuple(out)

    @property
    def independent_sources(self) -> tuple[str, ...]:
        return tuple(s for s in self.available if s != PUBCHEM_SOURCE)

    @property
    def resolves_cas(self) -> bool:
        """Whether any configured source could resolve a CAS number at all.

        When none is, EXT-01 did not run, and the honest report of that is a line
        in the run summary saying clearance is weaker -- not a medium finding on
        every record saying the number resolved nowhere. The same distinction
        applies to EXT-04: "we looked and found nothing" is a finding about a
        record, "we could not look" is a fact about the run.
        """
        return bool(
            len(self.registry)
            or (self.common_chemistry_dir and self.common_chemistry_dir.is_dir())
            or (self.pubchem_dir and self.pubchem_dir.is_dir())
        )


def _load_json(path: Path) -> dict | None:
    try:
        return json.loads(path.read_text())
    except (OSError, ValueError) as exc:
        log.warning("unreadable cache file %s: %s", path, exc)
        return None


def _clean_key(raw: str | None) -> str | None:
    """An InChIKey with the ``InChIKey=`` prefix removed, or None."""
    if not raw:
        return None
    return raw.replace("InChIKey=", "").strip() or None


def registry_candidate(evidence: Evidence, cas: str) -> Candidate | None:
    """What the SciFinder export says. The only independent source with full coverage."""
    row = evidence.registry.get(cas)
    if row is None:
        return None
    return Candidate(
        source=REGISTRY_SOURCE,
        independent=True,
        inchikey=_clean_key(row.inchikey),
        formula=row.molecular_formula or None,
        name=row.registry_name,
        url="",
        detail=row.source_pdf,
    )


def common_chemistry_candidate(evidence: Evidence, cas: str) -> Candidate | None:
    """What CAS Common Chemistry says, distinguishing a negative from an outage."""
    directory = evidence.common_chemistry_dir
    if not directory or not directory.is_dir():
        return None
    path = directory / f"{cas}.json"
    if not path.exists():
        return None
    blob = _load_json(path)
    if blob is None:
        return None

    http_status = blob.get("http_status")
    status = blob.get("status")
    if status == "ok" and isinstance(blob.get("detail"), dict):
        detail = blob["detail"]
        return Candidate(
            source=COMMON_CHEMISTRY_SOURCE,
            independent=True,
            inchikey=_clean_key(detail.get("inchiKey")),
            formula=formula_mod.strip_markup(detail.get("molecularFormula") or "")
            or None,
            name=detail.get("name") or "",
            url=f"https://commonchemistry.cas.org/detail?cas_rn={cas}",
        )
    if status == "notfound" or http_status == 404:
        return Candidate(
            source=COMMON_CHEMISTRY_SOURCE, independent=True, available=True
        )
    # Anything else is a failure that was cached, not an answer.
    return Candidate(
        source=COMMON_CHEMISTRY_SOURCE,
        independent=True,
        available=False,
        detail=f"cached HTTP {http_status}",
    )


def pubchem_candidates(evidence: Evidence, cas: str) -> list[Candidate]:
    """Every cached PubChem record for a CAS number, not merely the first.

    A CAS number resolving to several CIDs judged on whichever came back first
    invented 3 stereo mismatches and 7 wrong salt forms across 22 records, one of
    which had 18 candidates.
    """
    directory = evidence.pubchem_dir
    if not directory or not directory.is_dir():
        return []
    path = directory / f"{cas}.json"
    if not path.exists():
        return []
    blob = _load_json(path)
    if blob is None:
        return []

    cids_status = blob.get("cids_status")
    property_status = blob.get("property_status")
    total_cids = len(blob.get("cids") or [])

    # A cached failure is not a negative. Reading these fields is the whole fix:
    # nothing in the prototype ever did, so an outage and a 404 were identical.
    if cids_status not in (200, 404, None) or (
        property_status not in (200, None) and not blob.get("properties")
    ):
        return [
            Candidate(
                source=PUBCHEM_SOURCE,
                independent=False,
                available=False,
                detail=f"cached HTTP {cids_status or property_status}",
            )
        ]

    entries: list[tuple[object, dict]] = []
    if blob.get("properties"):
        entries.append((blob.get("cid"), blob["properties"]))
    for cid, props in (blob.get("alt_cids") or {}).items():
        if props:
            entries.append((cid, props))

    out: list[Candidate] = []
    for cid, props in entries:
        key = _clean_key(props.get("InChIKey"))
        if not key:
            continue
        smiles = next((props[k] for k in SMILES_KEYS if props.get(k)), "")
        out.append(
            Candidate(
                source=PUBCHEM_SOURCE,
                independent=False,
                inchikey=key,
                formula=props.get("MolecularFormula") or None,
                name=props.get("IUPACName") or "",
                url=f"https://pubchem.ncbi.nlm.nih.gov/compound/{cid}",
                detail=(
                    f"CID {cid}"
                    + (f" of {total_cids} returned" if total_cids > 1 else "")
                ),
            )
        )
        if not smiles:
            log.debug("PubChem CID %s has no SMILES under any known key", cid)
    if not out and not entries:
        return [Candidate(source=PUBCHEM_SOURCE, independent=False, available=True)]
    return out


def classify(candidate: Candidate, ctx: RecordContext) -> str:
    """How a candidate's structure relates to the drawn one."""
    if not candidate.available:
        return UNAVAILABLE
    if not candidate.inchikey:
        return UNRESOLVED

    drawn = ctx.structure.inchikey
    parent = ctx.structure.base_inchikey
    if drawn and candidate.inchikey == drawn:
        return EXACT
    if drawn and candidate.inchikey[:14] == drawn[:14]:
        return SKELETON
    if parent and candidate.inchikey[:14] == parent[:14]:
        return PARENT_ONLY
    return MISMATCH


def resolve_cas(evidence: Evidence, ctx: RecordContext) -> Verdict:
    """The best-supported answer to "does this CAS number denote what was drawn?".

    Independent sources are preferred on a tie, so a PubChem agreement never
    displaces an independent verdict of equal rank.
    """
    candidates: list[Candidate] = []
    registry = registry_candidate(evidence, ctx.cas)
    if registry is not None:
        candidates.append(registry)
    common = common_chemistry_candidate(evidence, ctx.cas)
    if common is not None:
        candidates.append(common)
    candidates.extend(pubchem_candidates(evidence, ctx.cas))

    if not candidates:
        return Verdict(
            status=UNRESOLVED,
            candidate=None,
            independent=False,
            note="no cached source holds this CAS number, so it was not checked",
        )

    scored = [
        (RANK[classify(c, ctx)], not c.independent, i) for i, c in enumerate(candidates)
    ]
    best_rank, _, best_index = min(scored)
    winner = candidates[best_index]
    status = classify(winner, ctx)

    others = [
        f"{c.label} gives {c.inchikey}"
        for i, c in enumerate(candidates)
        if i != best_index and c.inchikey and c.inchikey != winner.inchikey
    ]
    note = f"{winner.label} says {winner.inchikey or 'nothing'}"
    if others:
        note += "; " + "; ".join(others[:3])
    if best_rank == RANK[UNAVAILABLE]:
        note += "; re-fetch before treating this as a negative"
    return Verdict(
        status=status, candidate=winner, independent=winner.independent, note=note
    )


def ext01(evidence: Evidence, ctx: RecordContext) -> Iterator[Finding]:
    """EXT-01: does the CAS number denote the structure that was drawn?"""
    if not ctx.cas or not ctx.structure.parse:
        return
    if not evidence.resolves_cas:
        # No source is configured, so this check did not run. Reported once by
        # the summary rather than as a finding against all 290 records.
        return
    verdict = resolve_cas(evidence, ctx)
    if verdict.status == EXACT:
        return

    severity, message = {
        MISMATCH: (HIGH, "resolves to a different skeleton"),
        SKELETON: (
            MEDIUM,
            "matches only the skeleton; stereochemistry or protonation differs",
        ),
        PARENT_ONLY: (MEDIUM, "resolves to the free base or another salt form"),
        UNAVAILABLE: (MEDIUM, "could not be checked: a cached response was a failure"),
        UNRESOLVED: (MEDIUM, "resolves in no cached source"),
    }[verdict.status]

    yield ctx.finding(
        "EXT-01",
        severity,
        f"CAS {ctx.cas} {message}. {verdict.note}",
        evidence=verdict.candidate.url if verdict.candidate else "",
        independent=verdict.independent,
    )


def ext02(evidence: Evidence, ctx: RecordContext) -> Iterator[Finding]:
    """EXT-02: is this structure already in ChEBI?"""
    index = evidence.chebi
    if not len(index) or not ctx.structure.parse:
        return

    exact = index.exact(ctx.structure.inchikey)
    if exact:
        named = ", ".join(f"{cid} {index.label(cid)}".strip() for cid in exact[:3])
        extra = f" (and {len(exact) - 3} more)" if len(exact) > 3 else ""
        yield ctx.finding(
            "EXT-02",
            HIGH,
            f"already in ChEBI as {named}{extra}; submitting it again would "
            "duplicate an existing entry",
            evidence=f"https://www.ebi.ac.uk/chebi/searchId.do?chebiId={exact[0]}",
        )
        return

    relatives = index.skeleton(ctx.structure.inchikey)
    if relatives:
        named = ", ".join(f"{cid} {index.label(cid)}".strip() for cid in relatives[:3])
        extra = f" (and {len(relatives) - 3} more)" if len(relatives) > 3 else ""
        yield ctx.finding(
            "EXT-02",
            MEDIUM,
            f"shares its skeleton with {named}{extra}; not a duplicate, but the "
            "relationship should be stated",
            evidence=f"https://www.ebi.ac.uk/chebi/searchId.do?chebiId={relatives[0]}",
        )


def ext03(evidence: Evidence, ctx: RecordContext) -> Iterator[Finding]:
    """EXT-03: is the parent compound already in ChEBI, so a has-part link exists?

    Only an exact parent-key match counts. Accepting skeleton matches took this
    from 165 candidates to 206 and changed what it meant.
    """
    index = evidence.chebi
    if not len(index) or not ctx.structure.parse or not ctx.is_salt:
        return
    parents = index.exact(ctx.structure.base_inchikey)
    if not parents:
        return
    cid = parents[0]
    yield ctx.finding(
        "EXT-03",
        INFO,
        f"parent compound is already in ChEBI as {cid} {index.label(cid)}".rstrip()
        + "; candidate has-part link",
        evidence=f"https://www.ebi.ac.uk/chebi/searchId.do?chebiId={cid}",
    )


def ext04(evidence: Evidence, ctx: RecordContext) -> Iterator[Finding]:
    """EXT-04: does the registry formula agree with the stoichiometry drawn?"""
    if not ctx.structure.parse:
        return
    row = evidence.registry.get(ctx.cas)
    if row is None and not len(evidence.registry):
        # No registry at all: EXT-04 did not run, which the summary reports as
        # reduced coverage rather than as a per-record finding on all 290.
        return

    comparison = formula_mod.compare(
        row.molecular_formula if row else None,
        ctx.structure.formula,
        registry_name=row.registry_name if row else "",
        registry_ratio=row.name_ratio if row else "",
    )
    severity = {
        formula_mod.DISAGREE: HIGH,
        formula_mod.UNPARSEABLE: HIGH,
        formula_mod.RATIO_UNKNOWN: MEDIUM,
        formula_mod.NO_RECORD: LOW,
        formula_mod.CONVENTION: INFO,
    }.get(comparison.status)
    if severity is None:
        return

    yield ctx.finding(
        "EXT-04",
        severity,
        comparison.note,
        evidence=row.source_pdf if row else "",
    )


EXTERNAL_CHECKS = (ext01, ext02, ext03, ext04)


def run_external_checks(evidence: Evidence, ctx: RecordContext) -> list[Finding]:
    """Every external finding for one record."""
    from .checks import _validate

    out: list[Finding] = []
    for check in EXTERNAL_CHECKS:
        for finding in check(evidence, ctx):
            out.append(_validate(finding, check.__name__))
    return out
