"""Checks that compare a record against evidence from outside the file.

The single most important idea in the gate lives here. The submission SDFs were
generated by asking PubChem about each CAS number, so checking those SDFs against
PubChem is asking a source to confirm itself. On the reference batch that check
passed 284 of 290 records, and the number means almost nothing -- it mostly says
the generation step ran. Checked against evidence of a different origin, the same
batch showed efonidipine missing an ethanol fragment the circular check had called
flawless.

So every finding records whether its evidence was independent, and sources are
consulted worst-last:

1. the parsed SciFinder export -- independent, a versioned human artifact, and the
   only source with a row for all 290 records
2. CAS Common Chemistry -- independent, but thin: 82 of 291 cached numbers resolve
3. the PubChem cache -- circular, and used only when nothing else can speak

Two traps this layer exists to avoid, both of which produce a clean report:

**A transient failure is not a negative.** The caches persist ``cids_status``,
``property_status`` and ``http_status``, but nothing in the prototype ever read
them, so "PubChem has no such compound" and "PubChem was down for eight seconds"
were byte-for-byte indistinguishable and both came out as ``unresolved``. One
record was falsely unresolved that way. Here a non-200 cached response is its own
status, ``unavailable``, which says re-fetch rather than asserting a negative --
and it outranks ``unresolved`` so a real negative never masks an unknown.

**A CAS number resolving to several PubChem records must not be judged on the
first.** 22 of 290 resolved to more than one CID and one to eighteen. Judging
whichever came back first invented three stereo mismatches and seven wrong salt
forms, so every cached candidate is evaluated and the best-ranked one wins.
"""

from __future__ import annotations

import json
import logging
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path

from . import formula as formula_mod
from .casreg import EMPTY as EMPTY_REGISTRY
from .casreg import Registry
from .chebi_release import EMPTY as EMPTY_INDEX
from .chebi_release import Index
from .checks import (
    HIGH,
    INFO,
    LOW,
    MEDIUM,
    Finding,
    RecordContext,
    validate_finding,
)

log = logging.getLogger(__name__)

EXACT = "exact"
SKELETON = "skeleton"
PARENT_ONLY = "parent-only"
MISMATCH = "mismatch"
UNAVAILABLE = "unavailable"
UNRESOLVED = "unresolved"
# A source holds this CAS number and gave a key that disagrees, but it is a source
# whose structure strings cannot refute a drawing. Distinct from UNRESOLVED, which
# means no source holds the number at all: reusing UNRESOLVED made EXT-01 say
# "resolves in no cached source. CAS registry export says <key>" -- a sentence that
# contradicts itself, at `medium`, which holds. With no PubChem cache configured
# that was the *winning* verdict, so a registry-only run would have held the 25
# records of the reference batch whose registry key disagrees for benign reasons.
UNADJUDICATED = "cas-source-cannot-adjudicate"
# We could not produce a key to compare against, so nothing about the CAS number
# was established. Blaming the candidate for that is what MISMATCH used to do.
NOT_COMPARABLE = "not-comparable"

# Lower is a more informative answer. `unavailable` deliberately outranks
# `unresolved`: if one source could not be reached and another returned nothing,
# the honest combined verdict is "we do not know", not "it does not exist".
RANK = {
    EXACT: 0,
    SKELETON: 1,
    PARENT_ONLY: 2,
    MISMATCH: 3,
    # "we could not look" outranks "a source looked and we cannot use the answer",
    # which outranks "nothing holds this number", by the same reasoning as above.
    NOT_COMPARABLE: 4,
    UNAVAILABLE: 5,
    UNADJUDICATED: 6,
    UNRESOLVED: 7,
}

# The PubChem property key for an isomeric SMILES. PubChem renamed
# IsomericSMILES to SMILES in 2025 and still accepts the old name, returning HTTP
# 200 keyed by the new one -- so a fetcher that retries only on HTTP 400 never
# retries, and a consumer reading the old key silently gets nothing. All 291
# cached records carry SMILES and none carries IsomericSMILES. Read every spelling.
SMILES_KEYS = ("SMILES", "IsomericSMILES", "ConnectivitySMILES", "CanonicalSMILES")

REGISTRY_SOURCE = "CAS registry export"
COMMON_CHEMISTRY_SOURCE = "CAS Common Chemistry"
PUBCHEM_SOURCE = "PubChem"


@dataclass(frozen=True)
class Candidate:
    """One outside claim about what a CAS number denotes."""

    source: str
    independent: bool
    inchikey: str | None = None
    formula: str | None = None
    name: str = ""
    url: str = ""
    available: bool = True
    detail: str = ""
    # Whether a non-match from this source is evidence of a defect, or merely a
    # source that cannot be compared. See :func:`classify`.
    can_refute: bool = True

    @property
    def label(self) -> str:
        return f"{self.source}{f' ({self.detail})' if self.detail else ''}"


@dataclass(frozen=True)
class Verdict:
    """What the outside sources collectively say about one record."""

    status: str
    candidate: Candidate | None
    independent: bool
    note: str = ""
    # Whether any independent source positively confirmed the drawn structure.
    # False with an exact status means the only confirmation is circular.
    corroborated: bool = False


@dataclass(frozen=True)
class Evidence:
    """Every reference source a run has available. All optional."""

    registry: Registry = EMPTY_REGISTRY
    chebi: Index = EMPTY_INDEX
    pubchem_dir: Path | None = None
    common_chemistry_dir: Path | None = None

    @property
    def available(self) -> tuple[str, ...]:
        """Which sources this run can actually consult, for the summary."""
        out = []
        if len(self.registry):
            out.append(REGISTRY_SOURCE)
        if self.common_chemistry_dir and self.common_chemistry_dir.is_dir():
            out.append(COMMON_CHEMISTRY_SOURCE)
        if self.pubchem_dir and self.pubchem_dir.is_dir():
            out.append(PUBCHEM_SOURCE)
        if len(self.chebi):
            out.append("ChEBI release")
        return tuple(out)

    @property
    def independent_sources(self) -> tuple[str, ...]:
        return tuple(s for s in self.available if s != PUBCHEM_SOURCE)

    @property
    def resolves_cas(self) -> bool:
        """Whether any configured source could resolve a CAS number at all.

        When none is, EXT-01 did not run, and the honest report of that is a line
        in the run summary saying clearance is weaker -- not a medium finding on
        every record saying the number resolved nowhere. The same distinction
        applies to EXT-04: "we looked and found nothing" is a finding about a
        record, "we could not look" is a fact about the run.
        """
        return bool(
            len(self.registry)
            or (self.common_chemistry_dir and self.common_chemistry_dir.is_dir())
            or (self.pubchem_dir and self.pubchem_dir.is_dir())
        )


def _load_json(path: Path) -> dict | None:
    """One cache file as a mapping, or None. Never raises on its contents.

    The shape is checked, not assumed. A well-formed JSON file whose top level is
    an array parsed cleanly and then reached `blob.get(...)`, so a cache written
    from a different shape aborted the external pass part-way through -- and with
    it every later record's EXT-01 through EXT-04, not just this one's. The cache
    writer lives outside this package, which is exactly why its output is treated
    as input.
    """
    try:
        loaded = json.loads(path.read_text())
    except (OSError, ValueError) as exc:
        log.warning("unreadable cache file %s: %s", path, exc)
        return None
    if not isinstance(loaded, dict):
        log.warning(
            "cache file %s holds a %s, not an object", path, type(loaded).__name__
        )
        return None
    return loaded


def _clean_key(raw: str | None) -> str | None:
    """An InChIKey with the ``InChIKey=`` prefix removed, or None."""
    if not raw:
        return None
    return raw.replace("InChIKey=", "").strip() or None


def registry_candidate(evidence: Evidence, cas: str) -> Candidate | None:
    """What the SciFinder export says. The only independent source with full coverage."""
    row = evidence.registry.get(cas)
    if row is None:
        return None
    return Candidate(
        source=REGISTRY_SOURCE,
        independent=True,
        can_refute=False,
        inchikey=_clean_key(row.inchikey),
        formula=row.molecular_formula or None,
        name=row.registry_name,
        url="",
        detail=row.source_pdf,
    )


def common_chemistry_candidate(evidence: Evidence, cas: str) -> Candidate | None:
    """What CAS Common Chemistry says, distinguishing a negative from an outage."""
    directory = evidence.common_chemistry_dir
    if not directory or not directory.is_dir():
        return None
    path = directory / f"{cas}.json"
    if not path.exists():
        return None
    blob = _load_json(path)
    if blob is None:
        return None

    http_status = blob.get("http_status")
    status = blob.get("status")
    if status == "ok" and isinstance(blob.get("detail"), dict):
        detail = blob["detail"]
        return Candidate(
            source=COMMON_CHEMISTRY_SOURCE,
            independent=True,
            can_refute=False,
            inchikey=_clean_key(detail.get("inchiKey")),
            formula=formula_mod.strip_markup(detail.get("molecularFormula") or "")
            or None,
            name=detail.get("name") or "",
            url=f"https://commonchemistry.cas.org/detail?cas_rn={cas}",
        )
    if status == "notfound" or http_status == 404:
        return Candidate(
            source=COMMON_CHEMISTRY_SOURCE, independent=True, available=True
        )
    # Anything else is a failure that was cached, not an answer.
    return Candidate(
        source=COMMON_CHEMISTRY_SOURCE,
        independent=True,
        available=False,
        detail=f"cached HTTP {http_status}",
    )


def pubchem_candidates(evidence: Evidence, cas: str) -> list[Candidate]:
    """Every cached PubChem record for a CAS number, not merely the first.

    A CAS number resolving to several CIDs judged on whichever came back first
    invented 3 stereo mismatches and 7 wrong salt forms across 22 records, one of
    which had 18 candidates.
    """
    directory = evidence.pubchem_dir
    if not directory or not directory.is_dir():
        return []
    path = directory / f"{cas}.json"
    if not path.exists():
        return []
    blob = _load_json(path)
    if blob is None:
        return []

    cids_status = _as_status(blob.get("cids_status"))
    property_status = _as_status(blob.get("property_status"))
    total_cids = len(blob.get("cids") or [])

    # A cached failure is not a negative. Reading these fields is the whole fix:
    # nothing in the prototype ever did, so an outage and a 404 were identical.
    if cids_status not in (200, 404, None) or (
        property_status not in (200, None) and not blob.get("properties")
    ):
        return [
            Candidate(
                source=PUBCHEM_SOURCE,
                independent=False,
                available=False,
                detail=f"cached HTTP {cids_status or property_status}",
            )
        ]

    entries: list[tuple[object, dict]] = []
    if blob.get("properties"):
        entries.append((blob.get("cid"), _properties(blob["properties"])))
    alt = blob.get("alt_cids")
    for cid, props in (alt if isinstance(alt, dict) else {}).items():
        if props:
            entries.append((cid, _properties(props)))

    out: list[Candidate] = []
    for cid, props in entries:
        key = _clean_key(props.get("InChIKey"))
        if not key:
            continue
        smiles = next((props[k] for k in SMILES_KEYS if props.get(k)), "")
        out.append(
            Candidate(
                source=PUBCHEM_SOURCE,
                independent=False,
                inchikey=key,
                formula=props.get("MolecularFormula") or None,
                name=props.get("IUPACName") or "",
                url=f"https://pubchem.ncbi.nlm.nih.gov/compound/{cid}",
                detail=(
                    f"CID {cid}"
                    + (f" of {total_cids} returned" if total_cids > 1 else "")
                ),
            )
        )
        if not smiles:
            log.debug("PubChem CID %s has no SMILES under any known key", cid)
    if not out:
        # `not entries` was the condition, so a blob that *did* hold entries but
        # none with an InChIKey returned nothing at all -- and `resolve_cas` then
        # said "no cached source holds this CAS number" about a number the cache
        # answered for. The verdict was right and the sentence was not, which is
        # the kind of note a chemist reads and then goes looking for a cache entry
        # that is already there.
        return [Candidate(source=PUBCHEM_SOURCE, independent=False, available=True)]
    return out


def _as_status(value) -> int | None:
    """An HTTP status as an int, whatever the cache writer persisted it as.

    Compared against 200 below, so a cache that stored "200" as a string marked
    every entry unavailable. The writer is outside this package; its output is
    input.
    """
    if isinstance(value, bool) or value is None:
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _properties(value) -> dict:
    """One property mapping, whichever shape the cache persisted.

    PubChem's own ``PropertyTable.Properties`` is a *list* of records, and the
    cache writer lives outside this package, so a cache written straight from the
    API response would make ``props.get(...)`` raise AttributeError part-way
    through a run. Reading the first entry of a list costs nothing and the failure
    it avoids is one that aborts the external pass for every later record too.
    """
    if isinstance(value, list):
        return value[0] if value and isinstance(value[0], dict) else {}
    return value if isinstance(value, dict) else {}


def classify(candidate: Candidate, ctx: RecordContext) -> str:
    """How a candidate's structure relates to the drawn one."""
    if not candidate.available:
        return UNAVAILABLE
    if not candidate.inchikey:
        return UNRESOLVED

    drawn = ctx.structure.inchikey
    parent = ctx.structure.base_inchikey
    if not drawn and not parent:
        # Our side has no key to compare. `Structure.parse` can be True while
        # `inchikey` is None, because an RDKit InChI failure is swallowed and
        # logged -- and with both keys None every comparison below is False, so a
        # refutable candidate fell through to MISMATCH and EXT-01 reported "CAS
        # resolves to a different skeleton" at high. That attributes to the CAS
        # number a failure that happened here.
        return NOT_COMPARABLE
    if drawn and candidate.inchikey == drawn:
        return EXACT
    if drawn and candidate.inchikey[:14] == drawn[:14]:
        return SKELETON
    if parent and candidate.inchikey[:14] == parent[:14]:
        return PARENT_ONLY
    if not candidate.can_refute:
        # A CAS source's structure string is unreliable for salts, so its
        # disagreement is not evidence of a defect. Measured across the 290-record
        # batch: treating the SciFinder export's InChIKey as authoritative turns 25
        # sound records into high findings. Every one is a drawing convention or a
        # legacy key format, not a defect -- 7-NINA sodium salt is registered as
        # the neutral acid plus Na against an ionic drawing, AY 9944 carries a
        # pre-standard "InChI=1/" key with the same skeleton block, cyanopindolol
        # hemifumarate is registered as "1/2C4H4O4" against a doubled drawing.
        # Stoichiometry is where a CAS source *is* authoritative, and EXT-04 reads
        # it from molecular_formula; that check caught all three real
        # disagreements in the batch.
        return UNADJUDICATED
    return MISMATCH


def gather_candidates(evidence: Evidence, cas: str) -> list[Candidate]:
    """Every outside claim about a CAS number, independent sources first.

    The order is load-bearing, not cosmetic. :func:`resolve_cas` picks the
    best-ranked candidate and keeps the earliest of equal ranks, so this ordering
    is what stops a circular confirmation from displacing an independent one of
    the same strength. Appending PubChem before the CAS sources would silently
    invert the preference the whole module is built on.
    """
    candidates: list[Candidate] = []
    registry = registry_candidate(evidence, cas)
    if registry is not None:
        candidates.append(registry)
    common = common_chemistry_candidate(evidence, cas)
    if common is not None:
        candidates.append(common)
    # Circular last: the SDFs were generated from PubChem.
    candidates.extend(pubchem_candidates(evidence, cas))
    return candidates


def resolve_cas(evidence: Evidence, ctx: RecordContext) -> Verdict:
    """The best-supported answer to "does this CAS number denote what was drawn?".

    The most informative verdict wins, with independence breaking a tie at equal
    rank, so an independent confirmation is never displaced by a circular one of
    the same strength. Two rules keep that honest:

    A CAS source cannot *refute*. Its structure strings are unreliable for salts,
    so :func:`classify` never lets one produce a mismatch -- see the measurement
    there. It can still confirm, and it cannot drag a verdict down either: a
    registry key matching only the skeleton must not override another source's
    exact match, or 22 sound records in the batch drop from exact to skeleton.

    When the winning confirmation comes from PubChem while an independent source
    was configured and could not corroborate it, the verdict is still exact but
    the run says so: the SDFs were generated from PubChem, so that is a source
    confirming itself, and :func:`ext01` records it at low severity rather than
    letting it read as verification.
    """
    # The normalised key, for the same reason decisions use it: a record spelling
    # its CAS "0557-66-4" should still find its registry row and its cache entry,
    # and be told about the spelling once by INT-04 rather than three times by
    # three checks that could not look it up.
    candidates = gather_candidates(evidence, ctx.cas_key)

    if not candidates:
        return Verdict(
            status=UNRESOLVED,
            candidate=None,
            independent=bool(evidence.independent_sources),
            note="no cached source holds this CAS number, so it was not checked",
            corroborated=False,
        )

    # Rank alone, because gather_candidates already orders independent sources
    # first and min() keeps the earliest of equal keys. An `not c.independent`
    # tiebreak used to sit here too; mutation testing showed it was dead -- the
    # ordering decides every tie it could have decided. One mechanism, pinned by
    # test_candidates_are_ordered_independent_first, beats two that agree.
    # Classified once per candidate. It ran three times -- for the ranking, for the
    # winner's status and again for corroboration -- and a classification that is
    # recomputed is a classification that can disagree with itself.
    statuses = [classify(c, ctx) for c in candidates]
    _, index = min((RANK[status], i) for i, status in enumerate(statuses))
    winner = candidates[index]
    status = statuses[index]

    corroborated = any(
        c.independent and s in (EXACT, SKELETON, PARENT_ONLY)
        for c, s in zip(candidates, statuses)
    )
    others = [
        f"{c.label} gives {c.inchikey}"
        for i, c in enumerate(candidates)
        if i != index and c.inchikey and c.inchikey != winner.inchikey
    ]
    note = f"{winner.label} says {winner.inchikey or 'nothing'}"
    if others:
        note += "; " + "; ".join(others[:3])
    if status == UNAVAILABLE:
        note += "; re-fetch before treating this as a negative"
    return Verdict(
        status=status,
        candidate=winner,
        independent=winner.independent,
        note=note,
        corroborated=corroborated,
    )


def ext01(evidence: Evidence, ctx: RecordContext) -> Iterator[Finding]:
    """EXT-01: does the CAS number denote the structure that was drawn?"""
    if not ctx.cas or not ctx.structure.parse:
        return
    if not evidence.resolves_cas:
        # No source is configured, so this check did not run. Reported once by
        # the summary rather than as a finding against all 290 records.
        return
    verdict = resolve_cas(evidence, ctx)
    if verdict.status == EXACT:
        if not verdict.corroborated and evidence.independent_sources:
            # Exact, but only PubChem says so, and PubChem is where this SDF came
            # from. Low severity: it holds nothing, and it stops "284 of 290
            # confirmed" from being read as independent verification.
            yield ctx.finding(
                "EXT-01",
                LOW,
                f"CAS {ctx.cas} matches the drawn structure, but only in the source "
                f"the file was generated from. {verdict.note}",
                evidence=verdict.candidate.url if verdict.candidate else "",
                independent=False,
            )
        return

    # EXT-05 for the two outcomes that mean no comparison happened, EXT-01 for the
    # ones that compared something. See ext05_declared: a waiver keyed on severity
    # could not tell "matches only the skeleton" from "the cache returned a 500",
    # and the shipped waivers are all written for the first.
    check, severity, message = {
        MISMATCH: ("EXT-01", HIGH, "resolves to a different skeleton"),
        SKELETON: (
            "EXT-01",
            MEDIUM,
            "matches only the skeleton; stereochemistry or protonation differs",
        ),
        PARENT_ONLY: (
            "EXT-01",
            MEDIUM,
            "resolves to the free base or another salt form",
        ),
        UNAVAILABLE: (
            "EXT-05",
            MEDIUM,
            "could not be checked: a cached response was a failure",
        ),
        UNRESOLVED: ("EXT-05", MEDIUM, "resolves in no cached source"),
        UNADJUDICATED: (
            "EXT-01",
            LOW,
            "is registered to another structure by a source whose structure "
            "strings cannot refute a drawing, so this is reported and not held",
        ),
        NOT_COMPARABLE: (
            "EXT-01",
            LOW,
            "could not be compared: the drawn structure yielded no InChIKey",
        ),
    }[verdict.status]

    yield ctx.finding(
        check,
        severity,
        f"CAS {ctx.cas} {message}. {verdict.note}",
        evidence=verdict.candidate.url if verdict.candidate else "",
        independent=verdict.independent,
    )


def ext02(evidence: Evidence, ctx: RecordContext) -> Iterator[Finding]:
    """EXT-02: is this structure already in ChEBI?"""
    index = evidence.chebi
    if not len(index) or not ctx.structure.parse:
        return

    exact = index.exact(ctx.structure.inchikey)
    if exact:
        named = ", ".join(f"{cid} {index.label(cid)}".strip() for cid in exact[:3])
        extra = f" (and {len(exact) - 3} more)" if len(exact) > 3 else ""
        yield ctx.finding(
            "EXT-02",
            HIGH,
            f"already in ChEBI as {named}{extra}; submitting it again would "
            "duplicate an existing entry",
            evidence=f"https://www.ebi.ac.uk/chebi/searchId.do?chebiId={exact[0]}",
        )
        return

    relatives = index.skeleton(ctx.structure.inchikey)
    if relatives:
        named = ", ".join(f"{cid} {index.label(cid)}".strip() for cid in relatives[:3])
        extra = f" (and {len(relatives) - 3} more)" if len(relatives) > 3 else ""
        yield ctx.finding(
            "EXT-02",
            LOW,
            f"shares its skeleton with {named}{extra}; not a duplicate, but the "
            "relationship should be stated",
            evidence=f"https://www.ebi.ac.uk/chebi/searchId.do?chebiId={relatives[0]}",
        )


def ext03(evidence: Evidence, ctx: RecordContext) -> Iterator[Finding]:
    """EXT-03: is the parent compound already in ChEBI, so a has-part link exists?

    Only an exact parent-key match counts. Accepting skeleton matches took this
    from 165 candidates to 206 and changed what it meant.
    """
    index = evidence.chebi
    if not len(index) or not ctx.structure.parse or not ctx.is_salt:
        return
    parents = index.exact(ctx.structure.base_inchikey)
    if not parents:
        return
    cid = parents[0]
    # Every candidate, up to three, as EXT-02 already does: `Index.exact` returns a
    # tuple because 1,453 keys in the release are held by more than one entry, and
    # naming only the first tells a curator to make one has-part link when there
    # may be a choice to make.
    named = ", ".join(f"{c} {index.label(c)}".rstrip() for c in parents[:3])
    extra = f" (and {len(parents) - 3} more)" if len(parents) > 3 else ""
    yield ctx.finding(
        "EXT-03",
        INFO,
        f"parent compound is already in ChEBI as {named}{extra}"
        "; candidate has-part link",
        evidence=f"https://www.ebi.ac.uk/chebi/searchId.do?chebiId={cid}",
    )


def ext04(evidence: Evidence, ctx: RecordContext) -> Iterator[Finding]:
    """EXT-04: does the registry formula agree with the stoichiometry drawn?"""
    if not ctx.structure.parse:
        return
    if not ctx.cas:
        # No number was looked up, so "no CAS registry row for this number" would
        # be describing a lookup that never happened. INT-03 reports the absent
        # field; ext01 already guards the same way.
        return
    row = evidence.registry.get(ctx.cas_key)
    if row is None and not len(evidence.registry):
        # No registry at all: EXT-04 did not run, which the summary reports as
        # reduced coverage rather than as a per-record finding on all 290.
        return

    comparison = formula_mod.compare(
        row.molecular_formula if row else None,
        ctx.structure.formula,
        registry_name=row.registry_name if row else "",
        registry_ratio=row.name_ratio if row else "",
    )
    severity = {
        formula_mod.DISAGREE: HIGH,
        formula_mod.RATIO_UNKNOWN: MEDIUM,
        formula_mod.NO_RECORD: LOW,
        formula_mod.CONVENTION: INFO,
    }.get(comparison.status)
    if comparison.status == formula_mod.UNPARSEABLE:
        # Attributed to whichever side could not be read. Both used to be HIGH,
        # which held a record at the gate's most severe level for a defect in the
        # *evidence* -- the opposite of the rule this module applies everywhere
        # else, that "we could not look" is a fact about the run and not about the
        # record. formula.py's own example is a vendor code that lost its space in
        # a hand-parsed SciFinder export. `Comparison.checked` already classes
        # UNPARSEABLE with the statuses that did not check anything; this makes the
        # severity agree with that.
        severity = HIGH if comparison.unparseable_side == "drawn" else MEDIUM
    if severity is None:
        return

    yield ctx.finding(
        "EXT-04",
        severity,
        comparison.note,
        evidence=row.source_pdf if row else "",
    )


EXTERNAL_CHECKS = (ext01, ext02, ext03, ext04)


def run_external_checks(evidence: Evidence, ctx: RecordContext) -> list[Finding]:
    """Every external finding for one record."""
    out: list[Finding] = []
    for check in EXTERNAL_CHECKS:
        for finding in check(evidence, ctx):
            out.append(validate_finding(finding, check.__name__))
    return out
