version: 1
disable_existing_loggers: True

formatters:
  detailed:
    class: logging.Formatter
    format: '%(asctime)-24s %(processName)-19s %(threadName)-11s %(name)-13s %(levelname)-8s %(message)s'
  simple: 
    class: logging.Formatter
    format: 'concatenator - %(levelname)-8s - %(message)s'

handlers: 
  console: 
    class: logging.StreamHandler
    level: INFO
    formatter: simple
  file: 
    class: logging.FileHandler
    filename: concatenator.log
    mode: w
    formatter: detailed

loggers:
  concatenator:
    level: DEBUG
    handlers: [console, file]
    propagate: False

root: 
  level: INFO
  handlers: [console, file]
